"""notification framework and dashboard layout

Revision ID: 086e5a7c8ae3
Revises: 7cc28a17b6a6
Create Date: 2026-07-14 20:23:43.673909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '086e5a7c8ae3'
down_revision: Union[str, Sequence[str], None] = '7cc28a17b6a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_layouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_dashboard_layouts_user')
    )
    op.add_column('notifications', sa.Column('category', sa.String(), server_default='system', nullable=False))
    op.add_column('notifications', sa.Column('entity_type', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('entity_id', sa.UUID(), nullable=True))
    op.add_column('notifications', sa.Column('action_url', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('sender_id', sa.UUID(), nullable=True))
    op.add_column('notifications', sa.Column('sender_name', sa.String(), nullable=True))
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'read_status'], unique=False)
    op.create_foreign_key(None, 'notifications', 'users', ['sender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_column('notifications', 'sender_name')
    op.drop_column('notifications', 'sender_id')
    op.drop_column('notifications', 'action_url')
    op.drop_column('notifications', 'entity_id')
    op.drop_column('notifications', 'entity_type')
    op.drop_column('notifications', 'category')
    op.drop_table('dashboard_layouts')
    # ### end Alembic commands ###
