"""add attendance check-in/out accuracy columns

Revision ID: 3679f1515cdd
Revises: a7f14eb00a17
Create Date: 2026-07-14 12:00:03.313141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3679f1515cdd'
down_revision: Union[str, Sequence[str], None] = 'a7f14eb00a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('check_in_accuracy', sa.Float(), nullable=True))
    op.add_column('attendance', sa.Column('check_out_accuracy', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'check_out_accuracy')
    op.drop_column('attendance', 'check_in_accuracy')
    # ### end Alembic commands ###
