"""message recipient_ids as string array (polymorphic: employee ids or department name)

Revision ID: 4990b2ac6d21
Revises: 3679f1515cdd
Create Date: 2026-07-14 15:10:22.663729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4990b2ac6d21'
down_revision: Union[str, Sequence[str], None] = '3679f1515cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'recipient_ids',
               existing_type=postgresql.ARRAY(sa.UUID()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'recipient_ids',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.UUID()),
               existing_nullable=True)
    # ### end Alembic commands ###
