"""calendar_event recipient_ids as string array

Revision ID: 7cc28a17b6a6
Revises: 4990b2ac6d21
Create Date: 2026-07-14 18:06:35.863520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cc28a17b6a6'
down_revision: Union[str, Sequence[str], None] = '4990b2ac6d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar_events', 'recipient_ids',
               existing_type=postgresql.ARRAY(sa.UUID()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar_events', 'recipient_ids',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.UUID()),
               existing_nullable=True)
    # ### end Alembic commands ###
