"""employee cv attachment fields

Revision ID: 807283509ab4
Revises: bc14da2ca2fb
Create Date: 2026-07-16 14:02:19.265617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '807283509ab4'
down_revision: Union[str, Sequence[str], None] = 'bc14da2ca2fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cv_storage_path', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cv_original_filename', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cv_mime_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cv_file_size', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('cv_uploaded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('cv_uploaded_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['cv_uploaded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'cv_uploaded_by')
    op.drop_column('users', 'cv_uploaded_at')
    op.drop_column('users', 'cv_file_size')
    op.drop_column('users', 'cv_mime_type')
    op.drop_column('users', 'cv_original_filename')
    op.drop_column('users', 'cv_storage_path')
    # ### end Alembic commands ###
