"""device tokens for push notifications

Revision ID: 9499f3ab1f87
Revises: f587f273218b
Create Date: 2026-07-21 21:59:25.175570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9499f3ab1f87'
down_revision: Union[str, Sequence[str], None] = 'f587f273218b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Backs the FCM push-notification pipeline (see services/push.py):
    # `token` is unique per physical app install, not per user, so the
    # same device re-registering under a different account reassigns the
    # existing row instead of duplicating it (upsert-by-token in
    # repositories/device_tokens.py). No soft-delete column - a dead push
    # token has no audit value once it can no longer receive anything.
    op.create_table('device_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('app_version', sa.String(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("platform IN ('ios', 'android', 'web')", name='ck_device_tokens_platform'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token', name='uq_device_tokens_token')
    )
    op.create_index('ix_device_tokens_user', 'device_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_device_tokens_user', table_name='device_tokens')
    op.drop_table('device_tokens')
    # ### end Alembic commands ###
