"""sales: simplified small-team workflow - lead distribution settings, customer setup, data-entry and export permissions

Hand-written (NOT autogenerated: autogenerate against this schema also emits DROP INDEX for ~30 FK indexes that
exist in the database but are not declared in models.py - unrelated to Sales and must never be dropped here).
Chained after the Sales dashboard / reports revision b6d1f3a8c294. ADDITIVE ONLY: one new table, one new NULLABLE column,
one new index, two permission catalog rows and four grants. Nothing existing is dropped, rewritten or backfilled; the
onboarding tables stay exactly as they are (dormant: the simplified workflow no longer creates onboarding records).

Upgrade
  1. sales_settings    the Sales Manager's workspace settings: ONE row (id = 1, CHECK), seeded here with automatic lead
                       distribution OFF. distribution_mode is the closed set ('equal') - simple deterministic round-robin
                       among the staff who may receive leads; last_assigned_user_id is the round-robin cursor.
  2. sales_customers.subscription_type   'trial' | 'paid' - what the Customer Setup started the JAZ company on. NULL for
                       customers converted before this revision (the Phase-4 flow never recorded it); the company's own
                       subscription columns stay the source of truth for dates.
  3. ix_sales_leads_creator_recent  (created_by, created_at DESC, id DESC) - "the latest N leads this person created",
                       asked on every lead edit / archive by a Lead Data Entry user.
  4. reference data ONLY: permission catalog rows `sales.settings.manage` and `sales.leads.export` and the approved grants:
       sales_manager    += sales.settings.manage, sales.leads.export
       sales_employee   += sales.customers.convert          (completes the Customer Setup of the leads assigned to them)
       lead_data_entry  += sales.leads.delete               (archive / restore - limited in code to their latest 10 leads)
     No users, leads, companies or customers are seeded.

Downgrade
  * REFUSES to run while any customer carries a subscription_type (that fact exists nowhere else) - export and clear it
    deliberately first.
  * otherwise removes exactly what upgrade added: the four grants (by role AND key - sales.customers.convert and
    sales.leads.delete themselves predate this revision and stay), the two catalog rows, the index, the column and the
    settings table.

Seed values are frozen literals on purpose (like the earlier Sales migrations). Role ids are the uuid5 values the Phase-1
migration created (namespace 6f0c1c1e-5a3a-4a0e-9d6a-2d0e5b7f0a10, name "jaz.staff_roles.<key>").

Revision ID: a3f8c2d7e915
Revises: b6d1f3a8c294
Create Date: 2026-09-25
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = 'a3f8c2d7e915'
down_revision: Union[str, Sequence[str], None] = 'b6d1f3a8c294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# --- frozen seed data -------------------------------------------------------
_PERMISSIONS = [
    # (key, description)
    ('sales.settings.manage', 'Change the Sales workspace settings (automatic lead distribution)'),
    ('sales.leads.export', "Export the leads within the caller's lead scope to Excel or PDF"),
]

_ROLE_IDS = {
    'sales_manager': '059b10fc-f166-53de-93d2-995b2c1910bd',
    'sales_employee': '50f936d3-b54c-5d2d-899d-7da0864b20a8',
    'lead_data_entry': 'ea635826-fe6b-5987-a14f-53f9a7e7b0af',
}
# Approved grants (2026-09-25, simplified workflow).
_GRANTS = [
    ('sales_manager', 'sales.settings.manage'),
    ('sales_manager', 'sales.leads.export'),
    ('sales_employee', 'sales.customers.convert'),
    ('lead_data_entry', 'sales.leads.delete'),
]

_DISTRIBUTION_MODES = "('equal')"
_SUBSCRIPTION_TYPES = "('trial','paid')"


def upgrade() -> None:
    # Fail fast instead of queueing behind a long transaction on users / sales_leads / sales_customers.
    op.execute("SET LOCAL lock_timeout = '5s'")

    # ---- 1. settings (one row) ----
    op.create_table(
        'sales_settings',
        sa.Column('id', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
        sa.Column('auto_distribution_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('distribution_mode', sa.String(), server_default=sa.text("'equal'"), nullable=False),
        sa.Column('last_assigned_user_id', sa.UUID(), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_by', sa.UUID(), nullable=True),
        # Users are soft-deleted in this platform; NO ACTION (default) matches every other FK to users.
        sa.ForeignKeyConstraint(['last_assigned_user_id'], ['users.id']),
        sa.ForeignKeyConstraint(['updated_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint('id = 1', name='ck_sales_settings_singleton'),
        sa.CheckConstraint(f"distribution_mode IN {_DISTRIBUTION_MODES}", name='ck_sales_settings_distribution_mode'),
    )
    op.execute("INSERT INTO sales_settings (id, auto_distribution_enabled, distribution_mode) VALUES (1, false, 'equal')")

    # ---- 2. what the customer setup started the company on ----
    op.add_column('sales_customers', sa.Column('subscription_type', sa.String(), nullable=True))
    op.create_check_constraint(
        'ck_sales_customers_subscription_type', 'sales_customers',
        f"subscription_type IS NULL OR subscription_type IN {_SUBSCRIPTION_TYPES}",
    )

    # ---- 3. "my latest leads" ----
    op.create_index(
        'ix_sales_leads_creator_recent', 'sales_leads', ['created_by', sa.text('created_at DESC'), sa.text('id DESC')],
    )

    # ---- 4. reference data only ----
    perms = sa.table('staff_permissions', sa.column('key', sa.String), sa.column('module', sa.String),
                     sa.column('description', sa.String))
    role_perms = sa.table('staff_role_permissions', sa.column('role_id', sa.UUID), sa.column('permission_key', sa.String))
    op.bulk_insert(perms, [{'key': k, 'module': 'sales', 'description': d} for k, d in _PERMISSIONS])
    op.bulk_insert(role_perms, [{'role_id': _ROLE_IDS[rk], 'permission_key': pk} for rk, pk in _GRANTS])


def downgrade() -> None:
    op.execute("SET LOCAL lock_timeout = '5s'")

    bind = op.get_bind()
    typed = bind.execute(sa.text("SELECT count(*) FROM sales_customers WHERE subscription_type IS NOT NULL")).scalar_one()
    if typed:
        raise RuntimeError(
            f"Refusing to downgrade: {typed} JAZ Sales customer(s) record whether they started on a trial or a paid "
            "subscription (sales_customers.subscription_type). Export it and clear the column deliberately before downgrading."
        )

    # Exactly the grants this revision added - by role AND key (the keys sales.customers.convert / sales.leads.delete are
    # older and keep their other grants). Frozen literals, never user input.
    for role_key, permission_key in _GRANTS:
        op.execute(
            f"DELETE FROM staff_role_permissions WHERE role_id = '{_ROLE_IDS[role_key]}' AND permission_key = '{permission_key}'"
        )
    in_list = ', '.join(f"'{k}'" for k, _ in _PERMISSIONS)
    op.execute(f"DELETE FROM staff_role_permissions WHERE permission_key IN ({in_list})")
    op.execute(f"DELETE FROM staff_permissions WHERE key IN ({in_list})")

    op.drop_index('ix_sales_leads_creator_recent', table_name='sales_leads')
    op.drop_constraint('ck_sales_customers_subscription_type', 'sales_customers', type_='check')
    op.drop_column('sales_customers', 'subscription_type')
    op.drop_table('sales_settings')
