"""sales: dashboard and reports (Phase 5) - permissions and reporting indexes

Hand-written (NOT autogenerated: autogenerate against this schema also emits DROP INDEX for ~30 FK indexes that
exist in the database but are not declared in models.py - unrelated to Sales and must never be dropped here).
Chained after the Sales customers / onboarding revision f4c8a1d92b63. Creates NO table and changes NO column: the dashboard
and the reports only read the tables Phases 2-4 created (everything is aggregated by SQL - see repositories/reports.py).

Upgrade
  1. reference data ONLY: the two Phase-5 permission catalog rows (sales.dashboard.view, sales.reports.view) and the approved
     role -> permission grants (Sales Manager, Sales Employee and Onboarding Employee; Lead Data Entry gets neither -
     metrics are opt-in, and what a section shows is still limited by the permissions of the records it counts). No users,
     leads or other data are seeded.
  2. three indexes for the period filters the reports run that no existing index serves:
       ix_sales_followups_due_at            follow-ups in a period, any status (the existing follow-up indexes are partial on
                                            `pending`, or lead-first)
       ix_sales_trials_started_at           trials started in a period (the existing one is lead-first)
       ix_sales_leads_closed_at             leads closed (won / lost) in a period - partial: only closed leads carry closed_at
     Everything else the reports filter on is already indexed by Phases 2-4 (leads by created_at / owner / stage / source /
     campaign, calls by time and employee, demos by scheduled time, onboarding by start and owner). Onboarding activations
     are counted with a FILTER over the records in scope (no range predicate), so they need no index of their own.

Downgrade
  Drops the three indexes and removes exactly the permission catalog rows and grants this revision added. There is no data to
  protect (no table), so it never refuses.

Seed values are frozen literals on purpose (like the earlier Sales migrations): a migration keeps meaning what it meant
when it was written, whatever backend/sales/permissions.py evolves into. Role ids are the uuid5 values the Phase-1 migration
created (namespace 6f0c1c1e-5a3a-4a0e-9d6a-2d0e5b7f0a10, name "jaz.staff_roles.<key>").

Revision ID: b6d1f3a8c294
Revises: f4c8a1d92b63
Create Date: 2026-09-24
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = 'b6d1f3a8c294'
down_revision: Union[str, Sequence[str], None] = 'f4c8a1d92b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# --- frozen seed data -------------------------------------------------------
_PERMISSIONS = [
    # (key, description)
    ('sales.dashboard.view', "Open the Sales dashboard (each section shows only what the caller's other permissions allow)"),
    ('sales.reports.view', "Open the Sales reports (each report also needs the permissions of the records it counts)"),
]

_ROLE_IDS = {
    'sales_manager': '059b10fc-f166-53de-93d2-995b2c1910bd',
    'sales_employee': '50f936d3-b54c-5d2d-899d-7da0864b20a8',
    'onboarding_employee': '31e4bee9-ec9f-5e27-ae61-d1f280a0aaff',
}
# Approved grants. Lead Data Entry gets NOTHING here. The Onboarding Employee gets the two keys but holds no lead / work-item
# permission, so the only section they can ever see is onboarding, within the records assigned to them.
_GRANTS = [
    (role, key) for role in ('sales_manager', 'sales_employee', 'onboarding_employee') for key, _ in _PERMISSIONS
]

# (name, table, columns, partial predicate or None)
_INDEXES = [
    ('ix_sales_followups_due_at', 'sales_followups', ['due_at'], None),
    ('ix_sales_trials_started_at', 'sales_trials', [sa.text('started_at DESC')], None),
    ('ix_sales_leads_closed_at', 'sales_leads', ['closed_at'], 'closed_at IS NOT NULL'),
]


def upgrade() -> None:
    # Fail fast instead of queueing behind a long transaction on the tables indexed below.
    op.execute("SET LOCAL lock_timeout = '5s'")

    # ---- 1. reference data only ----
    perms = sa.table('staff_permissions', sa.column('key', sa.String), sa.column('module', sa.String),
                     sa.column('description', sa.String))
    role_perms = sa.table('staff_role_permissions', sa.column('role_id', sa.UUID), sa.column('permission_key', sa.String))
    op.bulk_insert(perms, [{'key': k, 'module': 'sales', 'description': d} for k, d in _PERMISSIONS])
    op.bulk_insert(role_perms, [{'role_id': _ROLE_IDS[rk], 'permission_key': pk} for rk, pk in _GRANTS])

    # ---- 2. reporting indexes ----
    for name, table, columns, where in _INDEXES:
        op.create_index(name, table, columns, postgresql_where=sa.text(where) if where else None)


def downgrade() -> None:
    op.execute("SET LOCAL lock_timeout = '5s'")

    for name, table, _, _ in reversed(_INDEXES):
        op.drop_index(name, table_name=table)

    # Exactly the catalog rows this revision added, grants first (staff_role_permissions.permission_key is RESTRICT).
    # The keys are this file's own frozen literals, never user input.
    in_list = ', '.join(f"'{k}'" for k, _ in _PERMISSIONS)
    op.execute(f"DELETE FROM staff_role_permissions WHERE permission_key IN ({in_list})")
    op.execute(f"DELETE FROM staff_permissions WHERE key IN ({in_list})")
