"""JAZ Sales - Phase 1: internal-staff platform role + RBAC foundation

Hand-written (NOT autogenerated: autogenerate against this schema also emits
DROP INDEX for 29 FK indexes that exist in the database but are not declared
in models.py - unrelated to Sales and must never be dropped here).

Upgrade
  * widens users.ck_users_role to also allow 'jaz_staff' (the ONLY change to an
    existing object - no column is added to users, companies, or anything else)
  * creates the four RBAC tables: staff_permissions, staff_roles,
    staff_role_permissions, staff_user_roles
  * seeds REFERENCE data only: the 4 system roles, the Phase-1 permission
    catalog, and the approved role->permission grants. No users, no business
    data, no demo data.

Downgrade
  * REFUSES to run while any users row has role='jaz_staff' (soft-deleted rows
    included - the restored CHECK would reject them). It never converts or
    deletes users.
  * otherwise drops only the four tables created here and restores the
    original 3-value CHECK.

Seed values are frozen literals on purpose: a migration must keep meaning what
it meant when it was written, regardless of how the app-side catalog in
backend/sales/permissions.py evolves. Role ids are uuid5 values derived from a
fixed namespace so upgrade/downgrade/upgrade cycles reproduce identical rows.
    namespace = 6f0c1c1e-5a3a-4a0e-9d6a-2d0e5b7f0a10, name = "jaz.staff_roles.<key>"

Revision ID: bb595f6d8dae
Revises: 60b5feec85d9
Create Date: 2026-09-23
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'bb595f6d8dae'
down_revision: Union[str, Sequence[str], None] = '60b5feec85d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_OLD_ROLE_CHECK = "role IN ('super_admin','company_owner','employee')"
_NEW_ROLE_CHECK = "role IN ('super_admin','company_owner','employee','jaz_staff')"

# --- frozen seed data -------------------------------------------------------
_ROLES = [
    # (id, key, name_en, name_ar, description)
    ("059b10fc-f166-53de-93d2-995b2c1910bd", "sales_manager", "Sales Manager", "مدير المبيعات",
     "Manages Sales workload, assignments and the Sales team."),
    ("50f936d3-b54c-5d2d-899d-7da0864b20a8", "sales_employee", "Sales Employee", "موظف مبيعات",
     "Works assigned leads: calls, follow-ups, demos and pipeline updates."),
    ("ea635826-fe6b-5987-a14f-53f9a7e7b0af", "lead_data_entry", "Lead Data Entry", "مدخل بيانات العملاء المحتملين",
     "Creates and maintains lead data."),
    ("31e4bee9-ec9f-5e27-ae61-d1f280a0aaff", "onboarding_employee", "Onboarding Employee", "موظف التهيئة",
     "Runs the onboarding workflow for converted customers."),
]
_PERMISSIONS = [
    # (key, description)
    ("sales.access", "Open the JAZ Sales workspace"),
    ("sales.team.view", "View the internal Sales team and role definitions"),
    ("sales.staff.create", "Create internal staff accounts"),
    ("sales.staff.update", "Edit, deactivate and reset the password of internal staff accounts"),
    ("sales.staff.assign_roles", "Assign and revoke internal staff roles"),
]
# Approved grants. sales.staff.* are deliberately granted to NO role: only Super
# Admin (implicitly) holds them until a future migration explicitly grants them.
_GRANTS = [
    ("sales_manager", "sales.access"),
    ("sales_manager", "sales.team.view"),
    ("sales_employee", "sales.access"),
    ("lead_data_entry", "sales.access"),
    ("onboarding_employee", "sales.access"),
]


def upgrade() -> None:
    # Fail fast instead of queueing behind a long transaction on users (which
    # would in turn block every login on the whole platform).
    op.execute("SET LOCAL lock_timeout = '5s'")

    op.drop_constraint('ck_users_role', 'users', type_='check')
    op.create_check_constraint('ck_users_role', 'users', _NEW_ROLE_CHECK)

    op.create_table(
        'staff_permissions',
        sa.Column('key', sa.String(), nullable=False),
        sa.Column('module', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('key'),
    )

    op.create_table(
        'staff_roles',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('module', sa.String(), nullable=False),
        sa.Column('key', sa.String(), nullable=False),
        sa.Column('name_en', sa.String(), nullable=False),
        sa.Column('name_ar', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('key', name='uq_staff_roles_key'),
    )

    op.create_table(
        'staff_role_permissions',
        sa.Column('role_id', sa.UUID(), nullable=False),
        sa.Column('permission_key', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        # Grants vanish only together with their role.
        sa.ForeignKeyConstraint(['role_id'], ['staff_roles.id'], ondelete='CASCADE'),
        # A catalog permission can't be removed while any role still grants it.
        sa.ForeignKeyConstraint(['permission_key'], ['staff_permissions.key'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('role_id', 'permission_key'),
    )
    op.create_index('ix_staff_role_permissions_permission_key', 'staff_role_permissions', ['permission_key'])

    op.create_table(
        'staff_user_roles',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('role_id', sa.UUID(), nullable=False),
        sa.Column('granted_by', sa.UUID(), nullable=False),
        sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('revoked_by', sa.UUID(), nullable=True),
        # Users are soft-deleted in this platform, so grant history stays intact;
        # NO ACTION (default) matches every other FK to users.
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.ForeignKeyConstraint(['granted_by'], ['users.id']),
        sa.ForeignKeyConstraint(['revoked_by'], ['users.id']),
        # A role that has ever been assigned can't be hard-deleted.
        sa.ForeignKeyConstraint(['role_id'], ['staff_roles.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint('revoked_at IS NULL OR revoked_at >= granted_at',
                           name='ck_staff_user_roles_revoked_after_granted'),
    )
    # At most one ACTIVE grant per (user, role); revoked rows are kept as history.
    op.create_index('uq_staff_user_roles_active', 'staff_user_roles', ['user_id', 'role_id'],
                    unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    # Hot path: resolving a user's effective permissions on every Sales request.
    op.create_index('ix_staff_user_roles_user_active', 'staff_user_roles', ['user_id'],
                    unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('ix_staff_user_roles_role_id', 'staff_user_roles', ['role_id'])

    # ---- reference data only ----
    perms = sa.table('staff_permissions', sa.column('key', sa.String), sa.column('module', sa.String),
                     sa.column('description', sa.String))
    roles = sa.table('staff_roles', sa.column('id', sa.UUID), sa.column('module', sa.String),
                     sa.column('key', sa.String), sa.column('name_en', sa.String), sa.column('name_ar', sa.String),
                     sa.column('description', sa.Text), sa.column('is_system', sa.Boolean))
    role_perms = sa.table('staff_role_permissions', sa.column('role_id', sa.UUID),
                          sa.column('permission_key', sa.String))
    op.bulk_insert(perms, [{'key': k, 'module': 'sales', 'description': d} for k, d in _PERMISSIONS])
    op.bulk_insert(roles, [
        {'id': i, 'module': 'sales', 'key': k, 'name_en': en, 'name_ar': ar, 'description': d, 'is_system': True}
        for i, k, en, ar, d in _ROLES
    ])
    role_id_by_key = {k: i for i, k, *_ in _ROLES}
    op.bulk_insert(role_perms, [{'role_id': role_id_by_key[rk], 'permission_key': pk} for rk, pk in _GRANTS])


def downgrade() -> None:
    op.execute("SET LOCAL lock_timeout = '5s'")

    # Guard: counts EVERY row (incl. soft-deleted) because the restored CHECK
    # constrains all rows. Never silently convert or delete users.
    staff_count = op.get_bind().execute(sa.text("SELECT count(*) FROM users WHERE role = 'jaz_staff'")).scalar_one()
    if staff_count:
        raise RuntimeError(
            f"Refusing to downgrade: {staff_count} user(s) with role 'jaz_staff' exist. "
            "Remove or re-role them explicitly (a deliberate, reviewed action) before downgrading."
        )

    op.drop_table('staff_user_roles')
    op.drop_table('staff_role_permissions')
    op.drop_table('staff_roles')
    op.drop_table('staff_permissions')

    op.drop_constraint('ck_users_role', 'users', type_='check')
    op.create_check_constraint('ck_users_role', 'users', _OLD_ROLE_CHECK)
