"""initial schema

Revision ID: bbef066a6bf9
Revises: 
Create Date: 2026-07-13 20:05:51.951552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbef066a6bf9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # subscription_plans created first: companies.subscription_plan_id has a
    # (non-deferrable) FK to it.
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('max_employees', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('features', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_months > 0', name='ck_plans_duration_positive'),
    sa.CheckConstraint('max_employees > 0', name='ck_plans_max_employees_positive'),
    sa.CheckConstraint('price >= 0', name='ck_plans_price_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('qr_code', sa.Text(), nullable=False),
    sa.Column('qr_token', sa.String(), nullable=True),
    sa.Column('subscription_status', sa.String(), server_default='active', nullable=False),
    sa.Column('subscription_plan_id', sa.UUID(), nullable=True),
    sa.Column('subscription_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_price', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('subscription_duration_months', sa.Integer(), nullable=True),
    sa.Column('subscription_features', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('max_employees', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('attendance_latitude', sa.Float(), nullable=True),
    sa.Column('attendance_longitude', sa.Float(), nullable=True),
    sa.Column('attendance_radius_meters', sa.Float(), server_default='50.0', nullable=False),
    sa.Column('attendance_qr_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('attendance_settings_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attendance_settings_updated_by', sa.UUID(), nullable=True),
    sa.Column('attendance_settings_updated_by_name', sa.String(), nullable=True),
    sa.Column('working_days', sa.ARRAY(sa.Integer()), server_default='{0,1,2,3,4}', nullable=False),
    sa.Column('working_hours_start_time', sa.String(length=5), server_default='08:00', nullable=False),
    sa.Column('working_hours_end_time', sa.String(length=5), server_default='17:00', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("subscription_status IN ('active','expired','suspended')", name='ck_companies_subscription_status'),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # owner_id / attendance_settings_updated_by both reference users.id, but
    # users doesn't exist yet at this point (companies <-> users is a genuine
    # mutual FK cycle - see plan decision #3). Added via ALTER TABLE below,
    # right after 'users' is created.
    op.create_table('counters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('super_admin','company_owner','employee')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    # Other half of the companies<->users mutual FK cycle (see note above) -
    # both tables now exist, so these can be added as ALTER TABLE.
    op.create_foreign_key(
        'fk_companies_owner_id_users', 'companies', 'users', ['owner_id'], ['id'],
        deferrable=True, initially='DEFERRED',
    )
    op.create_foreign_key(
        'fk_companies_attendance_settings_updated_by_users', 'companies', 'users',
        ['attendance_settings_updated_by'], ['id'],
    )
    op.create_table('attendance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('employee_department', sa.String(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_in_latitude', sa.Float(), nullable=True),
    sa.Column('check_in_longitude', sa.Float(), nullable=True),
    sa.Column('check_out_latitude', sa.Float(), nullable=True),
    sa.Column('check_out_longitude', sa.Float(), nullable=True),
    sa.Column('distance_from_company_meters', sa.Float(), nullable=True),
    sa.Column('check_out_distance_meters', sa.Float(), nullable=True),
    sa.Column('working_duration_minutes', sa.Float(), nullable=True),
    sa.Column('device_info', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('present','late','absent')", name='ck_attendance_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('execution_time', sa.String(length=5), nullable=True),
    sa.Column('requires_proof', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('recurrence_type', sa.String(), server_default='daily', nullable=False),
    sa.Column('recurrence_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('head_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['head_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_departments_company_name')
    )
    op.create_table('message_recipients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('recipient_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='delivered', nullable=False),
    sa.Column('is_unread', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_starred', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('sender','recipient')", name='ck_message_recipients_role'),
    sa.CheckConstraint("status IN ('delivered','seen','accepted','completed','archived')", name='ck_message_recipients_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'recipient_id', name='uq_message_recipients_thread_recipient')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('parent_message_id', sa.UUID(), nullable=True),
    sa.Column('forwarded_from_id', sa.UUID(), nullable=True),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('sender_name', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(), server_default='normal', nullable=False),
    sa.Column('confidentiality', sa.String(), server_default='internal', nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('requires_acknowledgement', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('completion_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recipient_type', sa.String(), nullable=False),
    sa.Column('recipient_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('recipient_department', sa.String(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_forward', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("confidentiality IN ('public','internal','confidential','highly_confidential')", name='ck_messages_confidentiality'),
    sa.CheckConstraint("priority IN ('normal','important','urgent')", name='ck_messages_priority'),
    sa.CheckConstraint("recipient_type IN ('employee','department')", name='ck_messages_recipient_type'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['forwarded_from_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['parent_message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'reference_number', name='uq_messages_company_reference')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read_status', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('employee_name', sa.String(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('files', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('images', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('default_color', sa.String(), nullable=True),
    sa.Column('custom_color', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), server_default='normal', nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=True),
    sa.Column('all_day', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('location_type', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('online_link', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), server_default='company', nullable=False),
    sa.Column('recipient_type', sa.String(), server_default='owner', nullable=False),
    sa.Column('recipient_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('recurrence_type', sa.String(), server_default='none', nullable=False),
    sa.Column('recurrence_interval', sa.Integer(), server_default='1', nullable=False),
    sa.Column('recurrence_end_type', sa.String(), server_default='never', nullable=False),
    sa.Column('recurrence_end_value', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('linked_thread_id', sa.UUID(), nullable=True),
    sa.Column('meeting_notes_summary', sa.Text(), server_default='', nullable=False),
    sa.Column('meeting_notes_decisions', sa.Text(), server_default='', nullable=False),
    sa.Column('meeting_notes_action_items', sa.Text(), server_default='', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_by_name', sa.String(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_by_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('low','normal','high','critical')", name='ck_calendar_events_priority'),
    sa.CheckConstraint("recipient_type IN ('owner','employee','department','owner_plus_employees','company')", name='ck_calendar_events_recipient_type'),
    sa.CheckConstraint("recurrence_end_type IN ('never','after_count','on_date')", name='ck_calendar_events_recurrence_end_type'),
    sa.CheckConstraint("recurrence_type IN ('none','daily','weekly','monthly','yearly','custom')", name='ck_calendar_events_recurrence_type'),
    sa.CheckConstraint("visibility IN ('private','department','company','owner_only')", name='ck_calendar_events_visibility'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['linked_thread_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'reference_number', name='uq_calendar_events_company_reference')
    )
    op.create_table('daily_task_assignees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('daily_task_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daily_task_id'], ['daily_tasks.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('daily_task_id', 'employee_id', name='uq_daily_task_assignees_task_employee')
    )
    op.create_table('message_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('attachment_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('due_time', sa.String(length=5), nullable=True),
    sa.Column('requires_proof', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('proof_files', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('task_category', sa.String(), nullable=True),
    sa.Column('alert_delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('daily_task_id', sa.UUID(), nullable=True),
    sa.Column('occurrence_date', sa.Date(), nullable=True),
    sa.Column('execution_date', sa.Date(), nullable=True),
    sa.Column('execution_time', sa.String(length=5), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.UUID(), nullable=True),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("priority IN ('critical','high','medium','low')", name='ck_tasks_priority'),
    sa.CheckConstraint("status IN ('new','received','seen','in_progress','pending_review','completed','rejected','overdue','cancelled')", name='ck_tasks_status'),
    sa.CheckConstraint("task_category IN ('urgent','daily') OR task_category IS NULL", name='ck_tasks_category'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['daily_task_id'], ['daily_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('attachment_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_event_exceptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('occurrence_date', sa.Date(), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('override_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'occurrence_date', name='uq_calendar_exceptions_event_date')
    )
    op.create_table('calendar_event_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('participant_name', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('attendance_status', sa.String(), server_default='no_response', nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_attendance', sa.String(), nullable=True),
    sa.Column('attendance_marked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("attendance_status IN ('no_response','accepted','declined','tentative')", name='ck_calendar_participants_attendance_status'),
    sa.CheckConstraint("final_attendance IN ('attended','absent') OR final_attendance IS NULL", name='ck_calendar_participants_final_attendance'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'participant_id', name='uq_calendar_event_participants_event_participant')
    )
    op.create_table('calendar_event_reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('attachment_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_attachments')
    op.drop_table('calendar_event_reminders')
    op.drop_table('calendar_event_participants')
    op.drop_table('calendar_event_exceptions')
    op.drop_table('calendar_attachments')
    op.drop_table('tasks')
    op.drop_table('message_reminders')
    op.drop_table('message_attachments')
    op.drop_table('daily_task_assignees')
    op.drop_table('calendar_events')
    op.drop_table('reports')
    op.drop_table('payment_transactions')
    op.drop_table('notifications')
    op.drop_table('messages')
    op.drop_table('message_recipients')
    op.drop_table('departments')
    op.drop_table('daily_tasks')
    op.drop_table('audit_logs')
    op.drop_table('attendance')
    op.drop_constraint('fk_companies_attendance_settings_updated_by_users', 'companies', type_='foreignkey')
    op.drop_constraint('fk_companies_owner_id_users', 'companies', type_='foreignkey')
    op.drop_table('users')
    op.drop_table('subscription_plans')
    op.drop_table('counters')
    op.drop_table('companies')
    # ### end Alembic commands ###
