"""scheduled tasks, sequential workflow, announcements

Revision ID: bc14da2ca2fb
Revises: 086e5a7c8ae3
Create Date: 2026-07-15 20:20:40.591828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc14da2ca2fb'
down_revision: Union[str, Sequence[str], None] = '086e5a7c8ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_by_name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasks', sa.Column('scheduled_activation_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('sequence_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    # Manual: autogenerate doesn't diff CheckConstraint bodies. Adds
    # 'scheduled' (Scheduled Task, future activation) and 'pending_sequence'
    # (Sequential Workflow, waiting for a prior step) to the allowed task
    # statuses.
    op.drop_constraint('ck_tasks_status', 'tasks', type_='check')
    op.create_check_constraint(
        'ck_tasks_status',
        'tasks',
        "status IN ('new','received','seen','in_progress','pending_review','completed','rejected','overdue','cancelled','scheduled','pending_sequence')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('ck_tasks_status', 'tasks', type_='check')
    op.create_check_constraint(
        'ck_tasks_status',
        'tasks',
        "status IN ('new','received','seen','in_progress','pending_review','completed','rejected','overdue','cancelled')",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'sequence_order')
    op.drop_column('tasks', 'scheduled_activation_at')
    op.drop_table('announcements')
    # ### end Alembic commands ###
