"""exact-time trial expiry (companies.subscription_ends_exactly) and the dormant Onboarding Employee role

Hand-written (NOT autogenerated: autogenerate against this schema also emits DROP INDEX for ~30 FK indexes that
exist in the database but are not declared in models.py - unrelated and must never be dropped here).
Chained after the simplified-workflow revision a3f8c2d7e915. ADDITIVE / REVERSIBLE ONLY: nothing is dropped or deleted.

Upgrade
  1. companies.subscription_ends_exactly  boolean NOT NULL DEFAULT false. When true, subscription_end_date is an exact
     INSTANT and the platform's expiry check (services/auth.py::subscription_has_ended) ends the subscription at that
     moment; when false (every existing company, and everything the Super Admin's Activate / Renew set) the end date keeps
     its calendar-day meaning ("a subscription ending today stays active through the whole day"). Only a Sales trial sets
     it (exactly 7 x 24 hours from its creation). A constant default is a metadata-only change on PostgreSQL 11+ - no
     table rewrite, no long lock.
  2. the Onboarding Employee system role is RETIRED (staff_roles.is_active = false) - the RBAC's own mechanism for a role
     that must stop granting anything: its holders lose every permission it gave on their next request (server-side,
     services/access.py reads active roles only), it disappears from /roles and the team listing, and it can no longer be
     granted. The role row, its permission grants, every staff_user_roles grant (history), the onboarding tables and the
     onboarding API are all kept exactly as they are, so re-enabling it is setting is_active back to true.

Downgrade
  * REFUSES while any company has subscription_ends_exactly = true (dropping the column would silently give those trials
    the rest of their last calendar day) - end or convert those trials deliberately first.
  * otherwise re-activates the Onboarding Employee role and drops the column.

Revision ID: c5e1b9a4d2f7
Revises: a3f8c2d7e915
Create Date: 2026-09-25
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = 'c5e1b9a4d2f7'
down_revision: Union[str, Sequence[str], None] = 'a3f8c2d7e915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# uuid5 of the Phase-1 migration (namespace 6f0c1c1e-5a3a-4a0e-9d6a-2d0e5b7f0a10, name "jaz.staff_roles.onboarding_employee")
_ONBOARDING_ROLE_ID = '31e4bee9-ec9f-5e27-ae61-d1f280a0aaff'


def upgrade() -> None:
    # Fail fast instead of queueing behind a long transaction on companies / staff_roles.
    op.execute("SET LOCAL lock_timeout = '5s'")

    op.add_column(
        'companies',
        sa.Column('subscription_ends_exactly', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    )
    op.execute(f"UPDATE staff_roles SET is_active = false, updated_at = now() WHERE id = '{_ONBOARDING_ROLE_ID}'")


def downgrade() -> None:
    op.execute("SET LOCAL lock_timeout = '5s'")

    bind = op.get_bind()
    exact = bind.execute(sa.text("SELECT count(*) FROM companies WHERE subscription_ends_exactly")).scalar_one()
    if exact:
        raise RuntimeError(
            f"Refusing to downgrade: {exact} company subscription(s) end at an exact time (Sales trials, "
            "companies.subscription_ends_exactly). Dropping the column would extend them to the end of their last day. "
            "End or convert those trials deliberately before downgrading."
        )
    op.execute(f"UPDATE staff_roles SET is_active = true, updated_at = now() WHERE id = '{_ONBOARDING_ROLE_ID}'")
    op.drop_column('companies', 'subscription_ends_exactly')
