"""add missing fk indexes

Revision ID: ca3f9acc6d73
Revises: 05c0a2518ccd
Create Date: 2026-07-27 01:40:01.874880

Adds indexes on company_id/employee_id/user_id/etc. foreign keys that were
previously unindexed despite being the primary filter on nearly every list
endpoint (multi-tenant isolation always filters by company_id). On a
production-sized database, run this during a maintenance window or convert
the CREATE INDEX statements to CREATE INDEX CONCURRENTLY (outside this
migration's transaction) to avoid locking these tables under live traffic.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca3f9acc6d73'
down_revision: Union[str, Sequence[str], None] = '05c0a2518ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_announcements_company_id'), 'announcements', ['company_id'], unique=False)
    op.create_index(op.f('ix_attendance_company_id'), 'attendance', ['company_id'], unique=False)
    op.create_index(op.f('ix_attendance_employee_id'), 'attendance', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_events_employee_id'), 'attendance_events', ['employee_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_company_id'), 'audit_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_calendar_attachments_company_id'), 'calendar_attachments', ['company_id'], unique=False)
    op.create_index(op.f('ix_calendar_event_participants_company_id'), 'calendar_event_participants', ['company_id'], unique=False)
    op.create_index(op.f('ix_calendar_event_reminders_company_id'), 'calendar_event_reminders', ['company_id'], unique=False)
    op.create_index(op.f('ix_calendar_event_reminders_user_id'), 'calendar_event_reminders', ['user_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_company_id'), 'calendar_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_daily_task_assignees_employee_id'), 'daily_task_assignees', ['employee_id'], unique=False)
    op.create_index(op.f('ix_daily_tasks_company_id'), 'daily_tasks', ['company_id'], unique=False)
    op.create_index(op.f('ix_departments_company_id'), 'departments', ['company_id'], unique=False)
    op.create_index(op.f('ix_message_attachments_company_id'), 'message_attachments', ['company_id'], unique=False)
    op.create_index(op.f('ix_message_recipients_company_id'), 'message_recipients', ['company_id'], unique=False)
    op.create_index(op.f('ix_message_recipients_recipient_id'), 'message_recipients', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_message_reminders_company_id'), 'message_reminders', ['company_id'], unique=False)
    op.create_index(op.f('ix_message_reminders_user_id'), 'message_reminders', ['user_id'], unique=False)
    op.create_index(op.f('ix_messages_company_id'), 'messages', ['company_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_notifications_company_id'), 'notifications', ['company_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_company_id'), 'payment_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_user_id'), 'payment_transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_reports_company_id'), 'reports', ['company_id'], unique=False)
    op.create_index(op.f('ix_reports_employee_id'), 'reports', ['employee_id'], unique=False)
    op.create_index(op.f('ix_task_attachments_company_id'), 'task_attachments', ['company_id'], unique=False)
    op.create_index(op.f('ix_tasks_assigned_to'), 'tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_tasks_company_id'), 'tasks', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_index(op.f('ix_tasks_company_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to'), table_name='tasks')
    op.drop_index(op.f('ix_task_attachments_company_id'), table_name='task_attachments')
    op.drop_index(op.f('ix_reports_employee_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_company_id'), table_name='reports')
    op.drop_index(op.f('ix_payment_transactions_user_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_company_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_notifications_company_id'), table_name='notifications')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_company_id'), table_name='messages')
    op.drop_index(op.f('ix_message_reminders_user_id'), table_name='message_reminders')
    op.drop_index(op.f('ix_message_reminders_company_id'), table_name='message_reminders')
    op.drop_index(op.f('ix_message_recipients_recipient_id'), table_name='message_recipients')
    op.drop_index(op.f('ix_message_recipients_company_id'), table_name='message_recipients')
    op.drop_index(op.f('ix_message_attachments_company_id'), table_name='message_attachments')
    op.drop_index(op.f('ix_departments_company_id'), table_name='departments')
    op.drop_index(op.f('ix_daily_tasks_company_id'), table_name='daily_tasks')
    op.drop_index(op.f('ix_daily_task_assignees_employee_id'), table_name='daily_task_assignees')
    op.drop_index(op.f('ix_calendar_events_company_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_event_reminders_user_id'), table_name='calendar_event_reminders')
    op.drop_index(op.f('ix_calendar_event_reminders_company_id'), table_name='calendar_event_reminders')
    op.drop_index(op.f('ix_calendar_event_participants_company_id'), table_name='calendar_event_participants')
    op.drop_index(op.f('ix_calendar_attachments_company_id'), table_name='calendar_attachments')
    op.drop_index(op.f('ix_audit_logs_company_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_attendance_events_employee_id'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_employee_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_company_id'), table_name='attendance')
    op.drop_index(op.f('ix_announcements_company_id'), table_name='announcements')
    # ### end Alembic commands ###
