"""sales: leads foundation (Phase 2) - sources, campaigns, leads, activity timeline, permissions

Hand-written (NOT autogenerated: autogenerate against this schema also emits DROP INDEX for ~30 FK indexes that
exist in the database but are not declared in models.py - unrelated to Sales and must never be dropped here).
Chained after the Sales audit-trail revision 2d916a1a993e. Touches NO existing table: it only creates new
tables and inserts reference rows into the two Phase-1 RBAC catalog tables.

Upgrade
  1. sales_lead_sources     the 11 standard lead sources (reference data, seeded here)
  2. sales_campaigns        basic campaigns; unique by lower(btrim(name))
  3. sales_leads            the leads; CHECKs for stage / priority / lost reason (lost <=> reason), coordinates,
                            value, assignment and archive pairs; FKs to sources, campaigns (RESTRICT) and users;
                            indexes for the list filters and for duplicate detection (normalized columns)
  4. sales_lead_activities  the immutable lead timeline; UPDATE / DELETE / TRUNCATE rejected by triggers;
                            FK to sales_leads is RESTRICT
  5. reference data ONLY: the Phase-2 permission catalog rows and the approved role -> permission grants. No
     users, leads, campaigns or demo data are seeded.

Downgrade
  * REFUSES to run while sales_leads, sales_campaigns or sales_lead_activities hold any row - lead data and its
    history are never dropped silently. Archive/export them and remove them deliberately (the table owner has
    to disable the append-only trigger for the activities) before downgrading.
  * otherwise drops the four tables created here (+ the trigger function) and removes exactly the permission
    catalog rows and grants this revision added.

Seed values are frozen literals on purpose (like the Phase-1 migration): a migration keeps meaning what it meant
when it was written, whatever backend/sales/constants.py and permissions.py evolve into. Role ids are the uuid5
values the Phase-1 migration created (namespace 6f0c1c1e-5a3a-4a0e-9d6a-2d0e5b7f0a10, name
"jaz.staff_roles.<key>").

Revision ID: d764d5f44e91
Revises: 2d916a1a993e
Create Date: 2026-09-24
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'd764d5f44e91'
down_revision: Union[str, Sequence[str], None] = '2d916a1a993e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# --- frozen seed data -------------------------------------------------------
_SOURCES = [
    # (key, name_en, name_ar, sort_order)
    ('google_maps', 'Google Maps', 'خرائط جوجل', 10),
    ('website', 'Website', 'الموقع الإلكتروني', 20),
    ('facebook', 'Facebook', 'فيسبوك', 30),
    ('instagram', 'Instagram', 'إنستغرام', 40),
    ('tiktok', 'TikTok', 'تيك توك', 50),
    ('referral', 'Referral', 'إحالة', 60),
    ('cold_call', 'Cold Call', 'اتصال مباشر', 70),
    ('inbound', 'Inbound', 'وارد', 80),
    ('advertisement', 'Advertisement', 'إعلان', 90),
    ('manual_entry', 'Manual Entry', 'إدخال يدوي', 100),
    ('import', 'Import', 'استيراد', 110),
]

_PERMISSIONS = [
    # (key, description)
    ('sales.leads.view', "View leads within the caller's lead scope"),
    ('sales.leads.create', 'Create leads'),
    ('sales.leads.update', "Edit lead details within the caller's lead scope"),
    ('sales.leads.delete', "Archive and restore leads within the caller's lead scope"),
    ('sales.leads.change_stage', 'Move leads through the sales pipeline, including marking them won or lost'),
    ('sales.leads.assign', "Assign, reassign and unassign leads within the caller's lead scope"),
    ('sales.leads.override_duplicates', 'Continue past an exact duplicate of an existing lead or JAZ company'),
    ('sales.leads.scope_all', 'Lead scope: every lead'),
    ('sales.leads.scope_assigned', 'Lead scope: leads assigned to the caller (also makes the caller assignable)'),
    ('sales.leads.scope_intake', 'Lead scope: leads the caller created, and unassigned leads'),
    ('sales.campaigns.view', 'View sales campaigns'),
    ('sales.campaigns.manage', 'Create, edit and delete sales campaigns'),
]

_ROLE_IDS = {
    'sales_manager': '059b10fc-f166-53de-93d2-995b2c1910bd',
    'sales_employee': '50f936d3-b54c-5d2d-899d-7da0864b20a8',
    'lead_data_entry': 'ea635826-fe6b-5987-a14f-53f9a7e7b0af',
}
# Approved grants. Onboarding Employee gets nothing new: no lead access in Phase 2.
_GRANTS = [
    # Sales Manager: every lead, all lead actions, campaigns; may continue past exact duplicates
    *[('sales_manager', k) for k in (
        'sales.leads.view', 'sales.leads.create', 'sales.leads.update', 'sales.leads.delete',
        'sales.leads.change_stage', 'sales.leads.assign', 'sales.leads.override_duplicates',
        'sales.leads.scope_all', 'sales.campaigns.view', 'sales.campaigns.manage',
    )],
    # Sales Employee: only the leads assigned to them; works them and moves them through the pipeline
    *[('sales_employee', k) for k in (
        'sales.leads.view', 'sales.leads.update', 'sales.leads.change_stage',
        'sales.leads.scope_assigned', 'sales.campaigns.view',
    )],
    # Lead Data Entry: creates leads; only the ones they created + unassigned ones
    *[('lead_data_entry', k) for k in (
        'sales.leads.view', 'sales.leads.create', 'sales.leads.update',
        'sales.leads.scope_intake', 'sales.campaigns.view',
    )],
]

_STAGES = "('new','assigned','contacted','interested','demo_scheduled','demo_completed','trial','negotiation','won','lost')"
_PRIORITIES = "('low','medium','high')"
_LOST_REASONS = (
    "('too_expensive','not_interested','already_using_another_system','no_response','wrong_number',"
    "'business_closed','not_suitable','delayed_decision','competitor','other')"
)
_CAMPAIGN_STATUSES = "('active','paused','completed')"


def upgrade() -> None:
    # Fail fast instead of queueing behind a long transaction on users (the FKs below briefly lock it).
    op.execute("SET LOCAL lock_timeout = '5s'")

    # ---- 1. lead sources (reference data) ----
    op.create_table(
        'sales_lead_sources',
        sa.Column('key', sa.String(), nullable=False),
        sa.Column('name_en', sa.String(), nullable=False),
        sa.Column('name_ar', sa.String(), nullable=False),
        sa.Column('sort_order', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('key'),
    )

    # ---- 2. campaigns ----
    op.create_table(
        'sales_campaigns',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('source', sa.String(), nullable=True),
        sa.Column('status', sa.String(), server_default=sa.text("'active'"), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=True),
        sa.Column('end_date', sa.Date(), nullable=True),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['source'], ['sales_lead_sources.key'], ondelete='RESTRICT'),
        # Users are soft-deleted in this platform; NO ACTION (default) matches every other FK to users.
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint(f"status IN {_CAMPAIGN_STATUSES}", name='ck_sales_campaigns_status'),
        sa.CheckConstraint('start_date IS NULL OR end_date IS NULL OR end_date >= start_date', name='ck_sales_campaigns_dates'),
        sa.CheckConstraint("btrim(name) <> ''", name='ck_sales_campaigns_name'),
    )
    op.create_index('uq_sales_campaigns_name', 'sales_campaigns', [sa.text('lower(btrim(name))')], unique=True)
    op.create_index('ix_sales_campaigns_status', 'sales_campaigns', ['status'])
    op.create_index('ix_sales_campaigns_source', 'sales_campaigns', ['source'], postgresql_where=sa.text('source IS NOT NULL'))
    op.create_index('ix_sales_campaigns_created_by', 'sales_campaigns', ['created_by'])

    # ---- 3. leads ----
    op.create_table(
        'sales_leads',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('business_name', sa.String(), nullable=False),
        sa.Column('business_type', sa.String(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('contact_name', sa.String(), nullable=True),
        sa.Column('contact_position', sa.String(), nullable=True),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('whatsapp', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('website', sa.String(), nullable=True),
        sa.Column('country', sa.String(), nullable=True),
        sa.Column('city', sa.String(), nullable=True),
        sa.Column('address', sa.String(), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.Column('source', sa.String(), server_default=sa.text("'manual_entry'"), nullable=False),
        sa.Column('campaign_id', sa.UUID(), nullable=True),
        sa.Column('pipeline_stage', sa.String(), server_default=sa.text("'new'"), nullable=False),
        sa.Column('lost_reason', sa.String(), nullable=True),
        sa.Column('assigned_to', sa.UUID(), nullable=True),
        sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('priority', sa.String(), server_default=sa.text("'medium'"), nullable=False),
        sa.Column('estimated_value', sa.Numeric(14, 2), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('archived_by', sa.UUID(), nullable=True),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('name_norm', sa.String(), nullable=False),
        sa.Column('city_norm', sa.String(), nullable=True),
        sa.Column('phone_norm', sa.String(), nullable=True),
        sa.Column('whatsapp_norm', sa.String(), nullable=True),
        sa.Column('email_norm', sa.String(), nullable=True),
        sa.Column('website_norm', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['source'], ['sales_lead_sources.key'], ondelete='RESTRICT'),
        # A campaign that still has leads cannot be deleted - deleting a campaign never takes leads with it.
        sa.ForeignKeyConstraint(['campaign_id'], ['sales_campaigns.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['assigned_to'], ['users.id']),
        sa.ForeignKeyConstraint(['archived_by'], ['users.id']),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint(f"pipeline_stage IN {_STAGES}", name='ck_sales_leads_stage'),
        sa.CheckConstraint(f"priority IN {_PRIORITIES}", name='ck_sales_leads_priority'),
        sa.CheckConstraint(f"lost_reason IS NULL OR lost_reason IN {_LOST_REASONS}", name='ck_sales_leads_lost_reason'),
        sa.CheckConstraint("(pipeline_stage = 'lost') = (lost_reason IS NOT NULL)", name='ck_sales_leads_lost_reason_pair'),
        sa.CheckConstraint("(pipeline_stage IN ('won','lost')) = (closed_at IS NOT NULL)", name='ck_sales_leads_closed_at_pair'),
        sa.CheckConstraint('(assigned_to IS NULL) = (assigned_at IS NULL)', name='ck_sales_leads_assigned_pair'),
        sa.CheckConstraint('(archived_at IS NULL) = (archived_by IS NULL)', name='ck_sales_leads_archived_pair'),
        sa.CheckConstraint('(latitude IS NULL) = (longitude IS NULL)', name='ck_sales_leads_coords_pair'),
        sa.CheckConstraint(
            '(latitude IS NULL OR latitude BETWEEN -90 AND 90) AND (longitude IS NULL OR longitude BETWEEN -180 AND 180)',
            name='ck_sales_leads_coords_range',
        ),
        sa.CheckConstraint('estimated_value IS NULL OR estimated_value >= 0', name='ck_sales_leads_value'),
        sa.CheckConstraint("btrim(business_name) <> ''", name='ck_sales_leads_name'),
    )
    # listing: default order, per-owner / per-stage views, the unassigned intake pool
    op.create_index('ix_sales_leads_created_at', 'sales_leads', [sa.text('created_at DESC'), sa.text('id DESC')],
                    postgresql_where=sa.text('archived_at IS NULL'))
    op.create_index('ix_sales_leads_assigned_stage', 'sales_leads', ['assigned_to', 'pipeline_stage'],
                    postgresql_where=sa.text('archived_at IS NULL'))
    op.create_index('ix_sales_leads_stage', 'sales_leads', ['pipeline_stage'], postgresql_where=sa.text('archived_at IS NULL'))
    op.create_index('ix_sales_leads_unassigned', 'sales_leads', ['created_at'],
                    postgresql_where=sa.text('assigned_to IS NULL AND archived_at IS NULL'))
    op.create_index('ix_sales_leads_created_by', 'sales_leads', ['created_by'])
    op.create_index('ix_sales_leads_campaign_id', 'sales_leads', ['campaign_id'], postgresql_where=sa.text('campaign_id IS NOT NULL'))
    op.create_index('ix_sales_leads_source', 'sales_leads', ['source'])
    op.create_index('ix_sales_leads_archived_by', 'sales_leads', ['archived_by'], postgresql_where=sa.text('archived_by IS NOT NULL'))
    # duplicate detection: one equality lookup per identity key, plus the phone digit-tail lookups
    op.create_index('ix_sales_leads_phone_norm', 'sales_leads', ['phone_norm'], postgresql_where=sa.text('phone_norm IS NOT NULL'))
    op.create_index('ix_sales_leads_whatsapp_norm', 'sales_leads', ['whatsapp_norm'], postgresql_where=sa.text('whatsapp_norm IS NOT NULL'))
    op.create_index('ix_sales_leads_phone_tail', 'sales_leads', [sa.text('right(phone_norm, 9)')],
                    postgresql_where=sa.text('length(phone_norm) >= 9'))
    op.create_index('ix_sales_leads_whatsapp_tail', 'sales_leads', [sa.text('right(whatsapp_norm, 9)')],
                    postgresql_where=sa.text('length(whatsapp_norm) >= 9'))
    op.create_index('ix_sales_leads_email_norm', 'sales_leads', ['email_norm'], postgresql_where=sa.text('email_norm IS NOT NULL'))
    op.create_index('ix_sales_leads_website_norm', 'sales_leads', ['website_norm'], postgresql_where=sa.text('website_norm IS NOT NULL'))
    op.create_index('ix_sales_leads_name_city', 'sales_leads', ['name_norm', 'city_norm'], postgresql_where=sa.text('city_norm IS NOT NULL'))

    # ---- 4. the lead activity timeline (append-only) ----
    op.create_table(
        'sales_lead_activities',
        sa.Column('id', sa.UUID(), nullable=False),  # app-generated, like every other table
        sa.Column('seq', sa.BigInteger(), sa.Identity(always=True), nullable=False),  # monotonic order / cursor
        sa.Column('lead_id', sa.UUID(), nullable=False),
        sa.Column('event_type', sa.String(), nullable=False),
        sa.Column('actor_user_id', sa.UUID(), nullable=False),
        sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
        sa.Column('before_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('after_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('note', sa.Text(), nullable=True),
        sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column('correlation_id', sa.UUID(), nullable=False),
        # History can never be orphaned: a lead that has a timeline cannot be hard-deleted.
        sa.ForeignKeyConstraint(['lead_id'], ['sales_leads.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['actor_user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('seq', name='uq_sales_lead_activities_seq'),
        sa.CheckConstraint("event_type ~ '^[a-z][a-z0-9_]{2,63}$'", name='ck_sales_lead_activities_type'),
        sa.CheckConstraint(
            "before_data IS NULL OR (jsonb_typeof(before_data) = 'object' AND pg_column_size(before_data) <= 16384)",
            name='ck_sales_lead_activities_before',
        ),
        sa.CheckConstraint(
            "after_data IS NULL OR (jsonb_typeof(after_data) = 'object' AND pg_column_size(after_data) <= 16384)",
            name='ck_sales_lead_activities_after',
        ),
        sa.CheckConstraint("jsonb_typeof(metadata) = 'object' AND pg_column_size(metadata) <= 8192",
                           name='ck_sales_lead_activities_metadata'),
    )
    op.create_index('ix_sales_lead_activities_lead', 'sales_lead_activities', ['lead_id', sa.text('seq DESC')])
    op.create_index('ix_sales_lead_activities_actor', 'sales_lead_activities', ['actor_user_id', sa.text('seq DESC')])

    # Append-only, same mechanism as staff_audit_events: UPDATE / DELETE (per row) and TRUNCATE (per statement)
    # are rejected. This stops application bugs and injected statements; the table owner can still disable a
    # trigger, which is why retention/erasure has to be a deliberate, privileged action.
    op.execute("""
        CREATE FUNCTION sales_lead_activities_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION USING
                MESSAGE = 'sales_lead_activities is append-only: ' || TG_OP || ' is not allowed',
                ERRCODE = 'insufficient_privilege';
        END
        $$
    """)
    op.execute("""
        CREATE TRIGGER trg_sales_lead_activities_no_mutation
            BEFORE UPDATE OR DELETE ON sales_lead_activities
            FOR EACH ROW EXECUTE FUNCTION sales_lead_activities_append_only()
    """)
    op.execute("""
        CREATE TRIGGER trg_sales_lead_activities_no_truncate
            BEFORE TRUNCATE ON sales_lead_activities
            FOR EACH STATEMENT EXECUTE FUNCTION sales_lead_activities_append_only()
    """)

    # ---- 5. reference data only ----
    sources = sa.table('sales_lead_sources', sa.column('key', sa.String), sa.column('name_en', sa.String),
                       sa.column('name_ar', sa.String), sa.column('sort_order', sa.Integer))
    perms = sa.table('staff_permissions', sa.column('key', sa.String), sa.column('module', sa.String),
                     sa.column('description', sa.String))
    role_perms = sa.table('staff_role_permissions', sa.column('role_id', sa.UUID), sa.column('permission_key', sa.String))
    op.bulk_insert(sources, [{'key': k, 'name_en': en, 'name_ar': ar, 'sort_order': o} for k, en, ar, o in _SOURCES])
    op.bulk_insert(perms, [{'key': k, 'module': 'sales', 'description': d} for k, d in _PERMISSIONS])
    op.bulk_insert(role_perms, [{'role_id': _ROLE_IDS[rk], 'permission_key': pk} for rk, pk in _GRANTS])


def downgrade() -> None:
    op.execute("SET LOCAL lock_timeout = '5s'")

    # Guard: lead data and its history are never dropped silently (count(*) sees every row, archived included).
    bind = op.get_bind()
    counts = {
        table: bind.execute(sa.text(f"SELECT count(*) FROM {table}")).scalar_one()
        for table in ('sales_lead_activities', 'sales_leads', 'sales_campaigns')
    }
    if any(counts.values()):
        held = ', '.join(f"{n} in {table}" for table, n in counts.items() if n)
        raise RuntimeError(
            f"Refusing to downgrade: JAZ Sales lead data exists ({held}). Export/archive it and remove the rows "
            "deliberately (the table owner must disable the append-only trigger for sales_lead_activities) "
            "before downgrading."
        )

    op.drop_table('sales_lead_activities')  # takes its indexes and triggers with it
    op.execute("DROP FUNCTION sales_lead_activities_append_only()")
    op.drop_table('sales_leads')
    op.drop_table('sales_campaigns')
    op.drop_table('sales_lead_sources')

    # Exactly the catalog rows this revision added, grants first (staff_role_permissions.permission_key is RESTRICT).
    # The keys are this file's own frozen literals, never user input.
    in_list = ', '.join(f"'{k}'" for k, _ in _PERMISSIONS)
    op.execute(f"DELETE FROM staff_role_permissions WHERE permission_key IN ({in_list})")
    op.execute(f"DELETE FROM staff_permissions WHERE key IN ({in_list})")
