"""sales: calls, follow-ups, demos and trials (Phase 3) - tables and permissions

Hand-written (NOT autogenerated: autogenerate against this schema also emits DROP INDEX for ~30 FK indexes that
exist in the database but are not declared in models.py - unrelated to Sales and must never be dropped here).
Chained after the Sales leads revision d764d5f44e91. Touches NO existing table: it only creates new tables and
inserts reference rows into the two Phase-1 RBAC catalog tables. The work done on a lead is recorded in the
Phase-2 timeline (sales_lead_activities) with new event types - that table needs no change.

Upgrade
  1. sales_calls      a call made to a lead; result CHECK; duration 0..86400 s or NULL; FK to leads (RESTRICT)
  2. sales_followups  something to do about a lead by a due time, given to one employee; pending / completed /
                      cancelled; completed_at set exactly while completed
  3. sales_demos      a demo for a lead, given to one employee; scheduled / completed / cancelled / no_show;
                      completed_at set exactly while completed
  4. sales_trials     Sales-side trial tracking (NOT the platform subscription trial); active / completed /
                      cancelled; actual_end_at set exactly while NOT active; expected end after the start;
                      a partial UNIQUE index allows at most one ACTIVE trial per lead
  5. reference data ONLY: the eight Phase-3 permission catalog rows and the approved role -> permission grants
     (Sales Manager and Sales Employee; Lead Data Entry and Onboarding Employee get nothing). No users, leads,
     calls, follow-ups, demos or trials are seeded.

Downgrade
  * REFUSES to run while any of the four tables holds a row - work history is never dropped silently. Export the
    rows and remove them deliberately before downgrading.
  * otherwise drops the four tables created here (their indexes go with them) and removes exactly the permission
    catalog rows and grants this revision added.

Seed values are frozen literals on purpose (like the Phase-1/2 migrations): a migration keeps meaning what it meant
when it was written, whatever backend/sales/constants.py and permissions.py evolve into. Role ids are the uuid5
values the Phase-1 migration created (namespace 6f0c1c1e-5a3a-4a0e-9d6a-2d0e5b7f0a10, name
"jaz.staff_roles.<key>").

Revision ID: e3a9c5b07d12
Revises: d764d5f44e91
Create Date: 2026-09-24
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = 'e3a9c5b07d12'
down_revision: Union[str, Sequence[str], None] = 'd764d5f44e91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# --- frozen seed data -------------------------------------------------------
_PERMISSIONS = [
    # (key, description)
    ('sales.calls.view', "View calls logged on leads within the caller's lead scope"),
    ('sales.calls.manage', "Log and edit calls on leads within the caller's lead scope"),
    ('sales.followups.view', "View follow-ups on leads within the caller's lead scope"),
    ('sales.followups.manage', "Create, edit, complete and cancel follow-ups on leads within the caller's lead scope"),
    ('sales.demos.view', "View demos on leads within the caller's lead scope"),
    ('sales.demos.manage', "Schedule, reschedule, complete, cancel and mark as no-show the demos of leads within the caller's lead scope"),
    ('sales.trials.view', "View Sales-side trials on leads within the caller's lead scope"),
    ('sales.trials.manage', "Start, edit, complete and cancel Sales-side trials on leads within the caller's lead scope"),
]

_ROLE_IDS = {
    'sales_manager': '059b10fc-f166-53de-93d2-995b2c1910bd',
    'sales_employee': '50f936d3-b54c-5d2d-899d-7da0864b20a8',
}
# Approved grants. Lead Data Entry and Onboarding Employee get NOTHING here: no broad Phase-3 access is implied
# by the Phase-2 permissions they already hold.
_ALL_KEYS = [k for k, _ in _PERMISSIONS]
_GRANTS = [
    # Sales Manager: every kind of work item (scope: every lead - sales.leads.scope_all is a Phase-2 grant)
    *[('sales_manager', k) for k in _ALL_KEYS],
    # Sales Employee: works the items of the leads assigned to them (scope: sales.leads.scope_assigned)
    *[('sales_employee', k) for k in _ALL_KEYS],
]

_CALL_RESULTS = "('answered','no_answer','busy','wrong_number','interested','not_interested','call_back')"
_FOLLOWUP_STATUSES = "('pending','completed','cancelled')"
_DEMO_STATUSES = "('scheduled','completed','cancelled','no_show')"
_TRIAL_STATUSES = "('active','completed','cancelled')"
_MAX_CALL_SECONDS = 86400


def upgrade() -> None:
    # Fail fast instead of queueing behind a long transaction on users / sales_leads (the FKs below briefly lock them).
    op.execute("SET LOCAL lock_timeout = '5s'")

    # ---- 1. calls ----
    op.create_table(
        'sales_calls',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('lead_id', sa.UUID(), nullable=False),
        sa.Column('employee_id', sa.UUID(), nullable=False),
        sa.Column('called_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('duration_seconds', sa.Integer(), nullable=True),
        sa.Column('result', sa.String(), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        # A lead that has work history can never be hard-deleted (same protection as its timeline).
        sa.ForeignKeyConstraint(['lead_id'], ['sales_leads.id'], ondelete='RESTRICT'),
        # Users are soft-deleted in this platform; NO ACTION (default) matches every other FK to users.
        sa.ForeignKeyConstraint(['employee_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint(f"result IN {_CALL_RESULTS}", name='ck_sales_calls_result'),
        sa.CheckConstraint(
            f"duration_seconds IS NULL OR (duration_seconds >= 0 AND duration_seconds <= {_MAX_CALL_SECONDS})",
            name='ck_sales_calls_duration',
        ),
        sa.CheckConstraint('notes IS NULL OR char_length(notes) <= 5000', name='ck_sales_calls_notes'),
    )
    # one lead's calls, newest first / one employee's calls / the recent-calls list
    op.create_index('ix_sales_calls_lead_time', 'sales_calls', ['lead_id', sa.text('called_at DESC')])
    op.create_index('ix_sales_calls_employee_time', 'sales_calls', ['employee_id', sa.text('called_at DESC')])
    op.create_index('ix_sales_calls_called_at', 'sales_calls', [sa.text('called_at DESC')])

    # ---- 2. follow-ups ----
    op.create_table(
        'sales_followups',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('lead_id', sa.UUID(), nullable=False),
        sa.Column('assigned_to', sa.UUID(), nullable=False),
        sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('status', sa.String(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['lead_id'], ['sales_leads.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['assigned_to'], ['users.id']),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint(f"status IN {_FOLLOWUP_STATUSES}", name='ck_sales_followups_status'),
        sa.CheckConstraint("(status = 'completed') = (completed_at IS NOT NULL)", name='ck_sales_followups_completed_pair'),
        sa.CheckConstraint('notes IS NULL OR char_length(notes) <= 5000', name='ck_sales_followups_notes'),
    )
    op.create_index('ix_sales_followups_lead_due', 'sales_followups', ['lead_id', 'due_at'])
    # the hot paths: "my follow-ups" and the overdue / upcoming lists read only OPEN rows
    op.create_index('ix_sales_followups_assignee_open', 'sales_followups', ['assigned_to', 'due_at'],
                    postgresql_where=sa.text("status = 'pending'"))
    op.create_index('ix_sales_followups_open_due', 'sales_followups', ['due_at'], postgresql_where=sa.text("status = 'pending'"))
    op.create_index('ix_sales_followups_completed_at', 'sales_followups', [sa.text('completed_at DESC')],
                    postgresql_where=sa.text("status = 'completed'"))
    op.create_index('ix_sales_followups_created_by', 'sales_followups', ['created_by'])

    # ---- 3. demos ----
    op.create_table(
        'sales_demos',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('lead_id', sa.UUID(), nullable=False),
        sa.Column('assigned_to', sa.UUID(), nullable=False),
        sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('status', sa.String(), server_default=sa.text("'scheduled'"), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['lead_id'], ['sales_leads.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['assigned_to'], ['users.id']),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint(f"status IN {_DEMO_STATUSES}", name='ck_sales_demos_status'),
        sa.CheckConstraint("(status = 'completed') = (completed_at IS NOT NULL)", name='ck_sales_demos_completed_pair'),
        sa.CheckConstraint('notes IS NULL OR char_length(notes) <= 5000', name='ck_sales_demos_notes'),
    )
    op.create_index('ix_sales_demos_lead_time', 'sales_demos', ['lead_id', sa.text('scheduled_at DESC')])
    op.create_index('ix_sales_demos_assignee_open', 'sales_demos', ['assigned_to', 'scheduled_at'],
                    postgresql_where=sa.text("status = 'scheduled'"))
    op.create_index('ix_sales_demos_open_time', 'sales_demos', ['scheduled_at'], postgresql_where=sa.text("status = 'scheduled'"))
    op.create_index('ix_sales_demos_scheduled_at', 'sales_demos', [sa.text('scheduled_at DESC')])
    op.create_index('ix_sales_demos_created_by', 'sales_demos', ['created_by'])

    # ---- 4. trials (Sales-side tracking only) ----
    op.create_table(
        'sales_trials',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('lead_id', sa.UUID(), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('expected_end_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('actual_end_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('status', sa.String(), server_default=sa.text("'active'"), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['lead_id'], ['sales_leads.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint(f"status IN {_TRIAL_STATUSES}", name='ck_sales_trials_status'),
        sa.CheckConstraint("(status = 'active') = (actual_end_at IS NULL)", name='ck_sales_trials_end_pair'),
        sa.CheckConstraint('expected_end_at > started_at', name='ck_sales_trials_expected_end'),
        sa.CheckConstraint('actual_end_at IS NULL OR actual_end_at >= started_at', name='ck_sales_trials_actual_end'),
        sa.CheckConstraint('notes IS NULL OR char_length(notes) <= 5000', name='ck_sales_trials_notes'),
    )
    # "prevent multiple active trials for the same lead" - the database is the real guarantee
    op.create_index('uq_sales_trials_one_active', 'sales_trials', ['lead_id'], unique=True,
                    postgresql_where=sa.text("status = 'active'"))
    op.create_index('ix_sales_trials_lead_started', 'sales_trials', ['lead_id', sa.text('started_at DESC')])
    op.create_index('ix_sales_trials_active_end', 'sales_trials', ['expected_end_at'], postgresql_where=sa.text("status = 'active'"))
    op.create_index('ix_sales_trials_actual_end', 'sales_trials', [sa.text('actual_end_at DESC')],
                    postgresql_where=sa.text("status <> 'active'"))
    op.create_index('ix_sales_trials_created_by', 'sales_trials', ['created_by'])

    # ---- 5. reference data only ----
    perms = sa.table('staff_permissions', sa.column('key', sa.String), sa.column('module', sa.String),
                     sa.column('description', sa.String))
    role_perms = sa.table('staff_role_permissions', sa.column('role_id', sa.UUID), sa.column('permission_key', sa.String))
    op.bulk_insert(perms, [{'key': k, 'module': 'sales', 'description': d} for k, d in _PERMISSIONS])
    op.bulk_insert(role_perms, [{'role_id': _ROLE_IDS[rk], 'permission_key': pk} for rk, pk in _GRANTS])


def downgrade() -> None:
    op.execute("SET LOCAL lock_timeout = '5s'")

    # Guard: work history is never dropped silently (count(*) sees every row).
    bind = op.get_bind()
    counts = {
        table: bind.execute(sa.text(f"SELECT count(*) FROM {table}")).scalar_one()
        for table in ('sales_calls', 'sales_followups', 'sales_demos', 'sales_trials')
    }
    if any(counts.values()):
        held = ', '.join(f"{n} in {table}" for table, n in counts.items() if n)
        raise RuntimeError(
            f"Refusing to downgrade: JAZ Sales call / follow-up / demo / trial data exists ({held}). "
            "Export it and remove the rows deliberately before downgrading."
        )

    op.drop_table('sales_trials')      # each drop takes the table's indexes with it
    op.drop_table('sales_demos')
    op.drop_table('sales_followups')
    op.drop_table('sales_calls')

    # Exactly the catalog rows this revision added, grants first (staff_role_permissions.permission_key is RESTRICT).
    # The keys are this file's own frozen literals, never user input.
    in_list = ', '.join(f"'{k}'" for k, _ in _PERMISSIONS)
    op.execute(f"DELETE FROM staff_role_permissions WHERE permission_key IN ({in_list})")
    op.execute(f"DELETE FROM staff_permissions WHERE key IN ({in_list})")
