"""sales: a permission of its own for the Customer Setup (sales.customers.setup) - the Sales Employee no longer holds convert

Hand-written (NOT autogenerated: autogenerate against this schema also emits DROP INDEX for ~30 FK indexes that
exist in the database but are not declared in models.py - unrelated and must never be dropped here).
Chained after c5e1b9a4d2f7. Reference data only (permission catalog + role grants); no table or column changes.

Why: a3f8c2d7e915 let the Sales Employee complete the Customer Setup by granting them sales.customers.convert. That key also
opens the Phase-4 conversion (POST /leads/{id}/convert), which creates the company with NO subscription dates - a subscription
that never ends, outside the Trial (exactly 7 x 24 h) and Paid (the plan's period) rules. The setup therefore gets its own key,
and the Phase-4 conversion goes back to what it was approved as: the Sales Manager's (and the Super Admin's).

Upgrade
  * catalog row sales.customers.setup;
  * grants sales.customers.setup to sales_manager and sales_employee;
  * withdraws exactly one grant: (sales_employee, sales.customers.convert) - the one a3f8c2d7e915 added.
Downgrade
  * gives that grant back and removes exactly what upgrade added. Never refuses: no data depends on a grant.

Revision ID: e7a2d4c9b1f3
Revises: c5e1b9a4d2f7
Create Date: 2026-09-25
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = 'e7a2d4c9b1f3'
down_revision: Union[str, Sequence[str], None] = 'c5e1b9a4d2f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_PERMISSIONS = [
    ('sales.customers.setup',
     "Complete the Customer Setup (company, owner, trial / paid subscription, optional employees and tasks) of a lead "
     "within the caller's lead scope"),
]
_ROLE_IDS = {
    'sales_manager': '059b10fc-f166-53de-93d2-995b2c1910bd',
    'sales_employee': '50f936d3-b54c-5d2d-899d-7da0864b20a8',
}
_GRANTS = [('sales_manager', 'sales.customers.setup'), ('sales_employee', 'sales.customers.setup')]
_WITHDRAWN = [('sales_employee', 'sales.customers.convert')]


def upgrade() -> None:
    op.execute("SET LOCAL lock_timeout = '5s'")
    perms = sa.table('staff_permissions', sa.column('key', sa.String), sa.column('module', sa.String),
                     sa.column('description', sa.String))
    role_perms = sa.table('staff_role_permissions', sa.column('role_id', sa.UUID), sa.column('permission_key', sa.String))
    op.bulk_insert(perms, [{'key': k, 'module': 'sales', 'description': d} for k, d in _PERMISSIONS])
    op.bulk_insert(role_perms, [{'role_id': _ROLE_IDS[rk], 'permission_key': pk} for rk, pk in _GRANTS])
    # frozen literals, never user input
    for role_key, permission_key in _WITHDRAWN:
        op.execute(
            f"DELETE FROM staff_role_permissions WHERE role_id = '{_ROLE_IDS[role_key]}' AND permission_key = '{permission_key}'"
        )


def downgrade() -> None:
    op.execute("SET LOCAL lock_timeout = '5s'")
    role_perms = sa.table('staff_role_permissions', sa.column('role_id', sa.UUID), sa.column('permission_key', sa.String))
    op.bulk_insert(role_perms, [{'role_id': _ROLE_IDS[rk], 'permission_key': pk} for rk, pk in _WITHDRAWN])
    in_list = ', '.join(f"'{k}'" for k, _ in _PERMISSIONS)
    op.execute(f"DELETE FROM staff_role_permissions WHERE permission_key IN ({in_list})")
    op.execute(f"DELETE FROM staff_permissions WHERE key IN ({in_list})")
