"""sales: Data Batches, Master Batches, Sales attempts / Work Batches, work sessions and their Sales Manager permissions

Hand-written (NOT autogenerated: autogenerate against this schema also emits DROP INDEX for ~30 FK indexes that
exist in the database but are not declared in models.py - unrelated and must never be dropped here).
Chained after the Customer Setup permission revision e7a2d4c9b1f3. ADDITIVE ONLY: seven new tables, one new NULLABLE column
(`sales_leads.data_batch_id`), one trigger, three permission catalog rows and their grants. No existing row is changed, deleted or
backfilled (leads created before this revision simply belong to no Data Batch).

Upgrade
  1. sales_master_batches / sales_data_batches
       Every 100 leads entered by ALL Data Entry staff combined form one Data Batch (nobody owns it); every 10 full batches form
       one Master Batch. `sales_leads.data_batch_id` records which batch a lead entered (set once, never moved - a trigger refuses
       any change). The same trigger refuses changing who entered the lead (created_by, never) and when (created_at - unless a
       DBA / data-fix session deliberately sets `jaz.allow_lead_backdating = 'on'` for its own transaction; nothing in the
       application does, and the tests that backdate leads to exercise the period reports say so explicitly). At most ONE batch is `open` (partial unique index), so the
       "current batch" is unambiguous and two racing lead creations can never fill two batches at once.
  2. sales_lead_attempts
       One row per salesperson's attempt at one lead: what they first decided (accepted / rejected / wait_list), how it ended
       (result: accepted / rejected / released, NULL while pending on the wait list), with timestamps. A lead has at most one
       PENDING attempt (partial unique index) and its attempts are numbered 1, 2, ... - the whole history of who tried it, when,
       and how it went is kept forever.
  3. sales_work_batches / sales_batch_attempts / sales_batch_attempt_leads
       When a salesperson has recorded an outcome for 100 leads that are in no batch yet they become a Sales Work Batch: `open`
       while any lead is still pending, `closed` once every lead has a final result. A closed batch can be handed to another
       salesperson: a new ATTEMPT of the same batch over the SAME leads (membership rows - leads are never copied), the previous
       attempts staying as they were. At most one attempt of a batch is open (partial unique index).
  4. sales_work_sessions
       The persisted work sessions behind "work hours" (consecutive recorded work actions less than 15 minutes apart).
  5. reference data ONLY: the permission catalog rows sales.batches.view, sales.batches.reassign and sales.performance.view and their
     grants - Sales Manager ONLY (Sales Employee, Lead Data Entry and the retired Onboarding role get none). No batches, attempts,
     sessions, users or leads are seeded.

Downgrade
  * REFUSES to run while any of the seven tables holds a row or any lead carries a data_batch_id - batch, attempt and work history
    is never dropped silently. Export it and remove it deliberately before downgrading.
  * otherwise drops the trigger, the column and the seven tables and removes exactly the catalog rows and grants added here.

Seed values are frozen literals on purpose (like the earlier Sales migrations). Role ids are the uuid5 values the Phase-1 migration
created (namespace 6f0c1c1e-5a3a-4a0e-9d6a-2d0e5b7f0a10, name "jaz.staff_roles.<key>").

Revision ID: f2b6d8a1c4e9
Revises: e7a2d4c9b1f3
Create Date: 2026-09-26
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = 'f2b6d8a1c4e9'
down_revision: Union[str, Sequence[str], None] = 'e7a2d4c9b1f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_PERMISSIONS = [
    ('sales.batches.view',
     "View the Data Batches, Master Batches and Sales Work Batches, search every lead across them and trace a lead through them"),
    ('sales.batches.reassign', "Hand a completed Sales Work Batch to another Sales Employee for another attempt at the same leads"),
    ('sales.performance.view', "View the work statistics and work history of Data Entry and Sales employees"),
]
_MANAGER_ROLE_ID = '059b10fc-f166-53de-93d2-995b2c1910bd'
_GRANTS = [('sales_manager', k) for k, _ in _PERMISSIONS]
_ROLE_IDS = {'sales_manager': _MANAGER_ROLE_ID}

_TABLES = (
    'sales_work_sessions', 'sales_lead_attempts', 'sales_batch_attempt_leads', 'sales_batch_attempts', 'sales_work_batches',
)   # dropped in this order; the leads column, the data batches and the master batches follow
_DATA_STATUSES = "('open','full')"
_WORK_STATUSES = "('open','closed')"
_KINDS = "('initial','reassignment')"
_OUTCOMES = "('accepted','rejected','wait_list')"
_RESULTS = "('accepted','rejected','released')"

_TRIGGER_FN = """
CREATE FUNCTION sales_leads_entry_immutable() RETURNS trigger AS $$
BEGIN
    IF NEW.created_by IS DISTINCT FROM OLD.created_by THEN
        RAISE EXCEPTION 'sales_leads.created_by is immutable: who entered a lead is recorded permanently'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    IF NEW.created_at IS DISTINCT FROM OLD.created_at
       AND COALESCE(current_setting('jaz.allow_lead_backdating', true), '') <> 'on' THEN
        RAISE EXCEPTION 'sales_leads.created_at is immutable: when a lead was entered is recorded permanently'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    IF OLD.data_batch_id IS NOT NULL AND NEW.data_batch_id IS DISTINCT FROM OLD.data_batch_id THEN
        RAISE EXCEPTION 'sales_leads.data_batch_id is immutable: a lead never moves to another Data Batch'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql
"""


def _uuid_pk():
    return sa.Column('id', sa.UUID(), nullable=False)


def _created_at():
    return sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False)


def upgrade() -> None:
    op.execute("SET LOCAL lock_timeout = '5s'")

    # ---- 1. master and data batches ----
    op.create_table(
        'sales_master_batches',
        _uuid_pk(),
        sa.Column('seq', sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column('formed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        _created_at(),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('seq', name='uq_sales_master_batches_seq'),
    )
    op.create_table(
        'sales_data_batches',
        _uuid_pk(),
        sa.Column('seq', sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column('status', sa.String(), server_default=sa.text("'open'"), nullable=False),
        sa.Column('lead_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
        sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('master_batch_id', sa.UUID(), nullable=True),
        _created_at(),
        sa.ForeignKeyConstraint(['master_batch_id'], ['sales_master_batches.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('seq', name='uq_sales_data_batches_seq'),
        sa.CheckConstraint(f"status IN {_DATA_STATUSES}", name='ck_sales_data_batches_status'),
        sa.CheckConstraint('lead_count >= 0 AND lead_count <= 100', name='ck_sales_data_batches_count'),
        sa.CheckConstraint("(status = 'full') = (filled_at IS NOT NULL)", name='ck_sales_data_batches_filled_pair'),
        sa.CheckConstraint("status <> 'full' OR lead_count = 100", name='ck_sales_data_batches_full_is_100'),
        sa.CheckConstraint("master_batch_id IS NULL OR status = 'full'", name='ck_sales_data_batches_master_needs_full'),
    )
    # ONE open batch at a time: the "current batch" is unambiguous and the database refuses a second one
    op.create_index('uq_sales_data_batches_one_open', 'sales_data_batches', ['status'], unique=True,
                    postgresql_where=sa.text("status = 'open'"))
    op.create_index('ix_sales_data_batches_master', 'sales_data_batches', ['master_batch_id'],
                    postgresql_where=sa.text('master_batch_id IS NOT NULL'))
    op.create_index('ix_sales_data_batches_unmastered', 'sales_data_batches', ['seq'],
                    postgresql_where=sa.text("status = 'full' AND master_batch_id IS NULL"))

    op.add_column('sales_leads', sa.Column('data_batch_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_sales_leads_data_batch', 'sales_leads', 'sales_data_batches', ['data_batch_id'], ['id'], ondelete='RESTRICT')
    op.create_index('ix_sales_leads_data_batch', 'sales_leads', ['data_batch_id'], postgresql_where=sa.text('data_batch_id IS NOT NULL'))
    op.execute(_TRIGGER_FN)
    op.execute(
        "CREATE TRIGGER trg_sales_leads_entry_immutable BEFORE UPDATE OF created_by, created_at, data_batch_id ON sales_leads "
        "FOR EACH ROW EXECUTE FUNCTION sales_leads_entry_immutable()"
    )

    # ---- 3 (created before 2: attempts point at batch attempts). work batches ----
    op.create_table(
        'sales_work_batches',
        _uuid_pk(),
        sa.Column('seq', sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column('employee_id', sa.UUID(), nullable=False),          # the salesperson whose 100 leads formed it
        sa.Column('lead_count', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(), server_default=sa.text("'open'"), nullable=False),
        sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
        _created_at(),
        sa.ForeignKeyConstraint(['employee_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('seq', name='uq_sales_work_batches_seq'),
        sa.CheckConstraint(f"status IN {_WORK_STATUSES}", name='ck_sales_work_batches_status'),
        sa.CheckConstraint('lead_count > 0', name='ck_sales_work_batches_count'),
        sa.CheckConstraint("(status = 'closed') = (closed_at IS NOT NULL)", name='ck_sales_work_batches_closed_pair'),
    )
    op.create_index('ix_sales_work_batches_employee', 'sales_work_batches', ['employee_id', sa.text('created_at DESC')])
    op.create_index('ix_sales_work_batches_status', 'sales_work_batches', ['status', sa.text('created_at DESC')])

    op.create_table(
        'sales_batch_attempts',
        _uuid_pk(),
        sa.Column('work_batch_id', sa.UUID(), nullable=False),
        sa.Column('attempt_no', sa.Integer(), nullable=False),
        sa.Column('employee_id', sa.UUID(), nullable=False),
        sa.Column('kind', sa.String(), nullable=False),
        sa.Column('status', sa.String(), server_default=sa.text("'open'"), nullable=False),
        sa.Column('lead_count', sa.Integer(), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('started_by', sa.UUID(), nullable=False),             # the salesperson (initial) or the manager (reassignment)
        sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
        _created_at(),
        sa.ForeignKeyConstraint(['work_batch_id'], ['sales_work_batches.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['employee_id'], ['users.id']),
        sa.ForeignKeyConstraint(['started_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('work_batch_id', 'attempt_no', name='uq_sales_batch_attempts_no'),
        sa.CheckConstraint('attempt_no >= 1', name='ck_sales_batch_attempts_no'),
        sa.CheckConstraint(f"kind IN {_KINDS}", name='ck_sales_batch_attempts_kind'),
        sa.CheckConstraint(f"status IN {_WORK_STATUSES}", name='ck_sales_batch_attempts_status'),
        sa.CheckConstraint('lead_count > 0', name='ck_sales_batch_attempts_count'),
        sa.CheckConstraint("(status = 'closed') = (closed_at IS NOT NULL)", name='ck_sales_batch_attempts_closed_pair'),
        sa.CheckConstraint("(attempt_no = 1) = (kind = 'initial')", name='ck_sales_batch_attempts_first_is_initial'),
    )
    op.create_index('uq_sales_batch_attempts_one_open', 'sales_batch_attempts', ['work_batch_id'], unique=True,
                    postgresql_where=sa.text("status = 'open'"))
    op.create_index('ix_sales_batch_attempts_employee', 'sales_batch_attempts', ['employee_id', 'status'])

    op.create_table(
        'sales_batch_attempt_leads',
        sa.Column('batch_attempt_id', sa.UUID(), nullable=False),
        sa.Column('lead_id', sa.UUID(), nullable=False),
        sa.Column('ordinal', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['batch_attempt_id'], ['sales_batch_attempts.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['lead_id'], ['sales_leads.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('batch_attempt_id', 'lead_id'),
        sa.CheckConstraint('ordinal >= 1', name='ck_sales_batch_attempt_leads_ordinal'),
    )
    op.create_index('ix_sales_batch_attempt_leads_lead', 'sales_batch_attempt_leads', ['lead_id'])

    # ---- 2. lead attempts ----
    op.create_table(
        'sales_lead_attempts',
        _uuid_pk(),
        sa.Column('lead_id', sa.UUID(), nullable=False),
        sa.Column('employee_id', sa.UUID(), nullable=False),
        sa.Column('attempt_no', sa.Integer(), nullable=False),
        sa.Column('first_outcome', sa.String(), nullable=False),
        sa.Column('outcome_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('wait_listed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('result', sa.String(), nullable=True),
        sa.Column('result_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('recorded_by', sa.UUID(), nullable=False),
        sa.Column('batch_attempt_id', sa.UUID(), nullable=True),
        _created_at(),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['lead_id'], ['sales_leads.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['employee_id'], ['users.id']),
        sa.ForeignKeyConstraint(['recorded_by'], ['users.id']),
        sa.ForeignKeyConstraint(['batch_attempt_id'], ['sales_batch_attempts.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint('attempt_no >= 1', name='ck_sales_lead_attempts_no'),
        sa.CheckConstraint(f"first_outcome IN {_OUTCOMES}", name='ck_sales_lead_attempts_outcome'),
        sa.CheckConstraint(f"result IS NULL OR result IN {_RESULTS}", name='ck_sales_lead_attempts_result'),
        # the wait list is a timestamp and nothing more
        sa.CheckConstraint("(first_outcome = 'wait_list') = (wait_listed_at IS NOT NULL)", name='ck_sales_lead_attempts_wait_pair'),
        sa.CheckConstraint('(result IS NULL) = (result_at IS NULL)', name='ck_sales_lead_attempts_result_pair'),
        # a direct outcome IS the result; only a wait-listed attempt can be pending or released
        # (NULL-safe on purpose: a CHECK passes on NULL, so `result = first_outcome` alone would let a direct attempt sit pending)
        sa.CheckConstraint("first_outcome = 'wait_list' OR (result IS NOT NULL AND result = first_outcome)", name='ck_sales_lead_attempts_direct_is_final'),
        sa.CheckConstraint("result IS DISTINCT FROM 'released' OR first_outcome = 'wait_list'", name='ck_sales_lead_attempts_released'),
    )
    op.create_index('uq_sales_lead_attempts_no', 'sales_lead_attempts', ['lead_id', 'attempt_no'], unique=True)
    # a lead has at most ONE pending attempt
    op.create_index('uq_sales_lead_attempts_one_pending', 'sales_lead_attempts', ['lead_id'], unique=True,
                    postgresql_where=sa.text('result IS NULL'))
    op.create_index('ix_sales_lead_attempts_employee', 'sales_lead_attempts', ['employee_id', sa.text('outcome_at DESC')])
    # the employee's leads that are in no batch yet (the 100-lead pool)
    op.create_index('ix_sales_lead_attempts_unbatched', 'sales_lead_attempts', ['employee_id', 'outcome_at', 'id'],
                    postgresql_where=sa.text('batch_attempt_id IS NULL'))
    op.create_index('ix_sales_lead_attempts_batch_attempt', 'sales_lead_attempts', ['batch_attempt_id'],
                    postgresql_where=sa.text('batch_attempt_id IS NOT NULL'))
    op.create_index('ix_sales_lead_attempts_outcome_at', 'sales_lead_attempts', [sa.text('outcome_at DESC')])

    # ---- 4. work sessions ----
    op.create_table(
        'sales_work_sessions',
        _uuid_pk(),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('actions', sa.Integer(), server_default=sa.text('1'), nullable=False),
        _created_at(),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint('ended_at >= started_at', name='ck_sales_work_sessions_order'),
        sa.CheckConstraint('actions >= 1', name='ck_sales_work_sessions_actions'),
    )
    op.create_index('ix_sales_work_sessions_user_end', 'sales_work_sessions', ['user_id', sa.text('ended_at DESC')])
    op.create_index('ix_sales_work_sessions_user_start', 'sales_work_sessions', ['user_id', 'started_at'])

    # ---- 5. reference data only ----
    perms = sa.table('staff_permissions', sa.column('key', sa.String), sa.column('module', sa.String), sa.column('description', sa.String))
    role_perms = sa.table('staff_role_permissions', sa.column('role_id', sa.UUID), sa.column('permission_key', sa.String))
    op.bulk_insert(perms, [{'key': k, 'module': 'sales', 'description': d} for k, d in _PERMISSIONS])
    op.bulk_insert(role_perms, [{'role_id': _ROLE_IDS[rk], 'permission_key': pk} for rk, pk in _GRANTS])


def downgrade() -> None:
    op.execute("SET LOCAL lock_timeout = '5s'")

    bind = op.get_bind()
    held = {
        table: bind.execute(sa.text(f"SELECT count(*) FROM {table}")).scalar_one()
        for table in _TABLES + ('sales_data_batches', 'sales_master_batches')
    }
    held['sales_leads.data_batch_id'] = bind.execute(sa.text("SELECT count(*) FROM sales_leads WHERE data_batch_id IS NOT NULL")).scalar_one()
    if any(held.values()):
        detail = ', '.join(f"{n} in {table}" for table, n in held.items() if n)
        raise RuntimeError(
            f"Refusing to downgrade: JAZ Sales batch / attempt / work-history data exists ({detail}). "
            "Export it and remove it deliberately before downgrading."
        )

    in_list = ', '.join(f"'{k}'" for k, _ in _PERMISSIONS)
    op.execute(f"DELETE FROM staff_role_permissions WHERE permission_key IN ({in_list})")
    op.execute(f"DELETE FROM staff_permissions WHERE key IN ({in_list})")

    for table in _TABLES:
        op.drop_table(table)
    op.execute("DROP TRIGGER trg_sales_leads_entry_immutable ON sales_leads")
    op.execute("DROP FUNCTION sales_leads_entry_immutable()")
    op.drop_index('ix_sales_leads_data_batch', table_name='sales_leads')
    op.drop_constraint('fk_sales_leads_data_batch', 'sales_leads', type_='foreignkey')
    op.drop_column('sales_leads', 'data_batch_id')
    op.drop_table('sales_data_batches')
    op.drop_table('sales_master_batches')
