"""sales: customers and onboarding (Phase 4) - tables and permissions

Hand-written (NOT autogenerated: autogenerate against this schema also emits DROP INDEX for ~30 FK indexes that
exist in the database but are not declared in models.py - unrelated to Sales and must never be dropped here).
Chained after the Sales activities revision e3a9c5b07d12. Touches NO existing table: it only creates two new tables
and inserts reference rows into the two Phase-1 RBAC catalog tables. What happens to a customer is recorded in the
Phase-2 timeline (sales_lead_activities) with new event types - that table needs no change.

Upgrade
  1. sales_customers   a won lead that became a JAZ company: one row per lead and one per company (both UNIQUE),
                       status active / onboarding / activated; FK to the lead (RESTRICT) and to the company
                       (RESTRICT) - neither can be hard-deleted while a customer points at it
  2. sales_onboarding  the onboarding workflow of one customer (exactly one per customer, UNIQUE): stage won ->
                       assigned -> contacted -> setup_started -> company_configured -> employees_added -> training
                       -> activated; an owner exactly when the stage is not `won`; completed_at set exactly while
                       the stage is `activated`
  3. reference data ONLY: the seven Phase-4 permission catalog rows and the approved role -> permission grants
     (Sales Manager: convert / view customers, view / manage / assign / scope-all onboarding; Sales Employee: view
     customers; Onboarding Employee: view / manage onboarding in the assigned scope; Lead Data Entry gets nothing).
     No users, leads, companies, customers or onboarding records are seeded.

Downgrade
  * REFUSES to run while either table holds a row - customers are never dropped silently (a customer is the link
    between a lead and a real JAZ company). Export the rows and remove them deliberately before downgrading.
  * otherwise drops the two tables created here (their indexes go with them) and removes exactly the permission
    catalog rows and grants this revision added.

Seed values are frozen literals on purpose (like the Phase-1/2/3 migrations): a migration keeps meaning what it meant
when it was written, whatever backend/sales/constants.py and permissions.py evolve into. Role ids are the uuid5
values the Phase-1 migration created (namespace 6f0c1c1e-5a3a-4a0e-9d6a-2d0e5b7f0a10, name
"jaz.staff_roles.<key>").

Revision ID: f4c8a1d92b63
Revises: e3a9c5b07d12
Create Date: 2026-09-24
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = 'f4c8a1d92b63'
down_revision: Union[str, Sequence[str], None] = 'e3a9c5b07d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# --- frozen seed data -------------------------------------------------------
_PERMISSIONS = [
    # (key, description)
    ('sales.customers.view', "View customers whose lead is within the caller's lead scope"),
    ('sales.customers.convert', "Convert won leads within the caller's lead scope into a customer and a JAZ company"),
    ('sales.onboarding.view', "View onboarding records within the caller's onboarding scope"),
    ('sales.onboarding.manage', "Change the stage and keep the notes of onboarding records within the caller's onboarding scope"),
    ('sales.onboarding.assign', "Assign and reassign the onboarding employee of an onboarding record"),
    ('sales.onboarding.scope_all', "Onboarding scope: every onboarding record"),
    ('sales.onboarding.scope_assigned', "Onboarding scope: onboarding records assigned to the caller (also makes the caller assignable)"),
]

_ROLE_IDS = {
    'sales_manager': '059b10fc-f166-53de-93d2-995b2c1910bd',
    'sales_employee': '50f936d3-b54c-5d2d-899d-7da0864b20a8',
    'onboarding_employee': '31e4bee9-ec9f-5e27-ae61-d1f280a0aaff',
}
# Approved grants. Lead Data Entry gets NOTHING here, and Sales Employee cannot convert: nothing about these
# permissions is implied by the lead permissions a role already holds.
_GRANTS = [
    # Sales Manager: converts won leads, sees every customer (lead scope: sales.leads.scope_all is a Phase-2 grant),
    # and runs onboarding across the board
    ('sales_manager', 'sales.customers.view'),
    ('sales_manager', 'sales.customers.convert'),
    ('sales_manager', 'sales.onboarding.view'),
    ('sales_manager', 'sales.onboarding.manage'),
    ('sales_manager', 'sales.onboarding.assign'),
    ('sales_manager', 'sales.onboarding.scope_all'),
    # Sales Employee: sees the customers that came out of the leads assigned to them (scope: sales.leads.scope_assigned)
    ('sales_employee', 'sales.customers.view'),
    # Onboarding Employee: works the onboarding records assigned to them - and nothing else. No lead, no customer.
    ('onboarding_employee', 'sales.onboarding.view'),
    ('onboarding_employee', 'sales.onboarding.manage'),
    ('onboarding_employee', 'sales.onboarding.scope_assigned'),
]

_CUSTOMER_STATUSES = "('active','onboarding','activated')"
_ONBOARDING_STAGES = ("('won','assigned','contacted','setup_started','company_configured','employees_added',"
                      "'training','activated')")


def upgrade() -> None:
    # Fail fast instead of queueing behind a long transaction on users / companies / sales_leads (the FKs below
    # briefly lock them).
    op.execute("SET LOCAL lock_timeout = '5s'")

    # ---- 1. customers ----
    op.create_table(
        'sales_customers',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('lead_id', sa.UUID(), nullable=False),
        sa.Column('company_id', sa.UUID(), nullable=False),
        sa.Column('converted_by', sa.UUID(), nullable=False),
        sa.Column('converted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('status', sa.String(), server_default=sa.text("'active'"), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        # A lead / company that has a customer can never be hard-deleted (same protection as the lead's timeline).
        sa.ForeignKeyConstraint(['lead_id'], ['sales_leads.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
        # Users are soft-deleted in this platform; NO ACTION (default) matches every other FK to users.
        sa.ForeignKeyConstraint(['converted_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint(f"status IN {_CUSTOMER_STATUSES}", name='ck_sales_customers_status'),
    )
    # "repeating the same conversion must not create another company/customer" - the database is the real guarantee
    op.create_index('uq_sales_customers_lead', 'sales_customers', ['lead_id'], unique=True)
    op.create_index('uq_sales_customers_company', 'sales_customers', ['company_id'], unique=True)
    op.create_index('ix_sales_customers_status', 'sales_customers', ['status', sa.text('converted_at DESC')])
    op.create_index('ix_sales_customers_converted_at', 'sales_customers', [sa.text('converted_at DESC')])
    op.create_index('ix_sales_customers_converted_by', 'sales_customers', ['converted_by'])

    # ---- 2. onboarding ----
    op.create_table(
        'sales_onboarding',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('customer_id', sa.UUID(), nullable=False),
        sa.Column('assigned_to', sa.UUID(), nullable=True),
        sa.Column('stage', sa.String(), server_default=sa.text("'won'"), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['sales_customers.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['assigned_to'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint(f"stage IN {_ONBOARDING_STAGES}", name='ck_sales_onboarding_stage'),
        # an owner exactly when the onboarding has left its starting stage
        sa.CheckConstraint("(stage = 'won') = (assigned_to IS NULL)", name='ck_sales_onboarding_owner_pair'),
        sa.CheckConstraint("(stage = 'activated') = (completed_at IS NOT NULL)", name='ck_sales_onboarding_completed_pair'),
        sa.CheckConstraint('completed_at IS NULL OR completed_at >= started_at', name='ck_sales_onboarding_completed_after_start'),
        sa.CheckConstraint('notes IS NULL OR char_length(notes) <= 5000', name='ck_sales_onboarding_notes'),
    )
    op.create_index('uq_sales_onboarding_customer', 'sales_onboarding', ['customer_id'], unique=True)
    # "my onboarding" (the assigned scope) and the per-stage board
    op.create_index('ix_sales_onboarding_assignee_stage', 'sales_onboarding', ['assigned_to', 'stage'],
                    postgresql_where=sa.text('assigned_to IS NOT NULL'))
    op.create_index('ix_sales_onboarding_stage', 'sales_onboarding', ['stage', sa.text('started_at DESC')])
    op.create_index('ix_sales_onboarding_started_at', 'sales_onboarding', [sa.text('started_at DESC')])

    # ---- 3. reference data only ----
    perms = sa.table('staff_permissions', sa.column('key', sa.String), sa.column('module', sa.String),
                     sa.column('description', sa.String))
    role_perms = sa.table('staff_role_permissions', sa.column('role_id', sa.UUID), sa.column('permission_key', sa.String))
    op.bulk_insert(perms, [{'key': k, 'module': 'sales', 'description': d} for k, d in _PERMISSIONS])
    op.bulk_insert(role_perms, [{'role_id': _ROLE_IDS[rk], 'permission_key': pk} for rk, pk in _GRANTS])


def downgrade() -> None:
    op.execute("SET LOCAL lock_timeout = '5s'")

    # Guard: a customer is the link between a lead and a real JAZ company - never dropped silently
    # (count(*) sees every row).
    bind = op.get_bind()
    counts = {
        table: bind.execute(sa.text(f"SELECT count(*) FROM {table}")).scalar_one()
        for table in ('sales_customers', 'sales_onboarding')
    }
    if any(counts.values()):
        held = ', '.join(f"{n} in {table}" for table, n in counts.items() if n)
        raise RuntimeError(
            f"Refusing to downgrade: JAZ Sales customer / onboarding data exists ({held}). "
            "Export it and remove the rows deliberately before downgrading."
        )

    op.drop_table('sales_onboarding')      # each drop takes the table's indexes with it
    op.drop_table('sales_customers')

    # Exactly the catalog rows this revision added, grants first (staff_role_permissions.permission_key is RESTRICT).
    # The keys are this file's own frozen literals, never user input.
    in_list = ', '.join(f"'{k}'" for k, _ in _PERMISSIONS)
    op.execute(f"DELETE FROM staff_role_permissions WHERE permission_key IN ({in_list})")
    op.execute(f"DELETE FROM staff_permissions WHERE key IN ({in_list})")
